# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.java.home=C:/Program Files/Java/jdk-25.0.2
# Fabric Properties
minecraft_version=26.1
loader_version=0.19.0
# Mod Properties
mod_version=1.0-release+26.1
maven_group=net.kztmc.mc
archives_base_name=Teamviewer

fabric_version=0.145.1+26.1
yacl_version=3.9.7+26.1-fabric
modmenu_version=22.0.0-alpha.1
