// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: lunarclient/apollo/common/v1/color.proto
// Protobuf Java Version: 4.31.1

package lunarclient.apollo.common.v1;

@com.google.protobuf.Generated
public final class ColorOuterClass {
  private ColorOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      ColorOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ColorOrBuilder extends
      // @@protoc_insertion_point(interface_extends:lunarclient.apollo.common.v1.Color)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * The color, encoded as a RGB Integer. For example, 0xFFAABB represents
     * R = 0xFF, G = 0xAA, and B = 0xBB.
     * </pre>
     *
     * <code>int32 color = 1 [json_name = "color"];</code>
     * @return The color.
     */
    int getColor();
  }
  /**
   * <pre>
   * A RGB color.
   *
   * We use this instead of the ProtoBuf Color class to avoid the sheer
   * size of the additional types included with the Google WKT package.
   * </pre>
   *
   * Protobuf type {@code lunarclient.apollo.common.v1.Color}
   */
  public static final class Color extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:lunarclient.apollo.common.v1.Color)
      ColorOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 1,
        /* suffix= */ "",
        Color.class.getName());
    }
    // Use Color.newBuilder() to construct.
    private Color(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Color() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return lunarclient.apollo.common.v1.ColorOuterClass.internal_static_lunarclient_apollo_common_v1_Color_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return lunarclient.apollo.common.v1.ColorOuterClass.internal_static_lunarclient_apollo_common_v1_Color_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              lunarclient.apollo.common.v1.ColorOuterClass.Color.class, lunarclient.apollo.common.v1.ColorOuterClass.Color.Builder.class);
    }

    public static final int COLOR_FIELD_NUMBER = 1;
    private int color_ = 0;
    /**
     * <pre>
     * The color, encoded as a RGB Integer. For example, 0xFFAABB represents
     * R = 0xFF, G = 0xAA, and B = 0xBB.
     * </pre>
     *
     * <code>int32 color = 1 [json_name = "color"];</code>
     * @return The color.
     */
    @java.lang.Override
    public int getColor() {
      return color_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (color_ != 0) {
        output.writeInt32(1, color_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (color_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, color_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof lunarclient.apollo.common.v1.ColorOuterClass.Color)) {
        return super.equals(obj);
      }
      lunarclient.apollo.common.v1.ColorOuterClass.Color other = (lunarclient.apollo.common.v1.ColorOuterClass.Color) obj;

      if (getColor()
          != other.getColor()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + COLOR_FIELD_NUMBER;
      hash = (53 * hash) + getColor();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static lunarclient.apollo.common.v1.ColorOuterClass.Color parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lunarclient.apollo.common.v1.ColorOuterClass.Color parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lunarclient.apollo.common.v1.ColorOuterClass.Color parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lunarclient.apollo.common.v1.ColorOuterClass.Color parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lunarclient.apollo.common.v1.ColorOuterClass.Color parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lunarclient.apollo.common.v1.ColorOuterClass.Color parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lunarclient.apollo.common.v1.ColorOuterClass.Color parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static lunarclient.apollo.common.v1.ColorOuterClass.Color parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static lunarclient.apollo.common.v1.ColorOuterClass.Color parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static lunarclient.apollo.common.v1.ColorOuterClass.Color parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static lunarclient.apollo.common.v1.ColorOuterClass.Color parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static lunarclient.apollo.common.v1.ColorOuterClass.Color parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(lunarclient.apollo.common.v1.ColorOuterClass.Color prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * A RGB color.
     *
     * We use this instead of the ProtoBuf Color class to avoid the sheer
     * size of the additional types included with the Google WKT package.
     * </pre>
     *
     * Protobuf type {@code lunarclient.apollo.common.v1.Color}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:lunarclient.apollo.common.v1.Color)
        lunarclient.apollo.common.v1.ColorOuterClass.ColorOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return lunarclient.apollo.common.v1.ColorOuterClass.internal_static_lunarclient_apollo_common_v1_Color_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return lunarclient.apollo.common.v1.ColorOuterClass.internal_static_lunarclient_apollo_common_v1_Color_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                lunarclient.apollo.common.v1.ColorOuterClass.Color.class, lunarclient.apollo.common.v1.ColorOuterClass.Color.Builder.class);
      }

      // Construct using lunarclient.apollo.common.v1.ColorOuterClass.Color.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        color_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return lunarclient.apollo.common.v1.ColorOuterClass.internal_static_lunarclient_apollo_common_v1_Color_descriptor;
      }

      @java.lang.Override
      public lunarclient.apollo.common.v1.ColorOuterClass.Color getDefaultInstanceForType() {
        return lunarclient.apollo.common.v1.ColorOuterClass.Color.getDefaultInstance();
      }

      @java.lang.Override
      public lunarclient.apollo.common.v1.ColorOuterClass.Color build() {
        lunarclient.apollo.common.v1.ColorOuterClass.Color result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public lunarclient.apollo.common.v1.ColorOuterClass.Color buildPartial() {
        lunarclient.apollo.common.v1.ColorOuterClass.Color result = new lunarclient.apollo.common.v1.ColorOuterClass.Color(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(lunarclient.apollo.common.v1.ColorOuterClass.Color result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.color_ = color_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof lunarclient.apollo.common.v1.ColorOuterClass.Color) {
          return mergeFrom((lunarclient.apollo.common.v1.ColorOuterClass.Color)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(lunarclient.apollo.common.v1.ColorOuterClass.Color other) {
        if (other == lunarclient.apollo.common.v1.ColorOuterClass.Color.getDefaultInstance()) return this;
        if (other.getColor() != 0) {
          setColor(other.getColor());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                color_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int color_ ;
      /**
       * <pre>
       * The color, encoded as a RGB Integer. For example, 0xFFAABB represents
       * R = 0xFF, G = 0xAA, and B = 0xBB.
       * </pre>
       *
       * <code>int32 color = 1 [json_name = "color"];</code>
       * @return The color.
       */
      @java.lang.Override
      public int getColor() {
        return color_;
      }
      /**
       * <pre>
       * The color, encoded as a RGB Integer. For example, 0xFFAABB represents
       * R = 0xFF, G = 0xAA, and B = 0xBB.
       * </pre>
       *
       * <code>int32 color = 1 [json_name = "color"];</code>
       * @param value The color to set.
       * @return This builder for chaining.
       */
      public Builder setColor(int value) {

        color_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The color, encoded as a RGB Integer. For example, 0xFFAABB represents
       * R = 0xFF, G = 0xAA, and B = 0xBB.
       * </pre>
       *
       * <code>int32 color = 1 [json_name = "color"];</code>
       * @return This builder for chaining.
       */
      public Builder clearColor() {
        bitField0_ = (bitField0_ & ~0x00000001);
        color_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:lunarclient.apollo.common.v1.Color)
    }

    // @@protoc_insertion_point(class_scope:lunarclient.apollo.common.v1.Color)
    private static final lunarclient.apollo.common.v1.ColorOuterClass.Color DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new lunarclient.apollo.common.v1.ColorOuterClass.Color();
    }

    public static lunarclient.apollo.common.v1.ColorOuterClass.Color getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Color>
        PARSER = new com.google.protobuf.AbstractParser<Color>() {
      @java.lang.Override
      public Color parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Color> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Color> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public lunarclient.apollo.common.v1.ColorOuterClass.Color getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lunarclient_apollo_common_v1_Color_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lunarclient_apollo_common_v1_Color_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n(lunarclient/apollo/common/v1/color.pro" +
      "to\022\034lunarclient.apollo.common.v1\"\035\n\005Colo" +
      "r\022\024\n\005color\030\001 \001(\005R\005colorb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_lunarclient_apollo_common_v1_Color_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_lunarclient_apollo_common_v1_Color_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lunarclient_apollo_common_v1_Color_descriptor,
        new java.lang.String[] { "Color", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
