// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: lunarclient/apollo/common/v1/component.proto
// Protobuf Java Version: 4.31.1

package lunarclient.apollo.common.v1;

@com.google.protobuf.Generated
public final class ComponentOuterClass {
  private ComponentOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      ComponentOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  @java.lang.Deprecated public interface ComponentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:lunarclient.apollo.common.v1.Component)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string content = 1 [json_name = "content"];</code>
     * @return The content.
     */
    java.lang.String getContent();
    /**
     * <code>string content = 1 [json_name = "content"];</code>
     * @return The bytes for content.
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <code>.lunarclient.apollo.common.v1.Color color = 2 [json_name = "color"];</code>
     * @return Whether the color field is set.
     */
    boolean hasColor();
    /**
     * <code>.lunarclient.apollo.common.v1.Color color = 2 [json_name = "color"];</code>
     * @return The color.
     */
    lunarclient.apollo.common.v1.ColorOuterClass.Color getColor();
    /**
     * <code>.lunarclient.apollo.common.v1.Color color = 2 [json_name = "color"];</code>
     */
    lunarclient.apollo.common.v1.ColorOuterClass.ColorOrBuilder getColorOrBuilder();

    /**
     * <code>repeated .lunarclient.apollo.common.v1.Component.TextDecorator decorators = 3 [json_name = "decorators"];</code>
     * @return A list containing the decorators.
     */
    java.util.List<lunarclient.apollo.common.v1.ComponentOuterClass.Component.TextDecorator> getDecoratorsList();
    /**
     * <code>repeated .lunarclient.apollo.common.v1.Component.TextDecorator decorators = 3 [json_name = "decorators"];</code>
     * @return The count of decorators.
     */
    int getDecoratorsCount();
    /**
     * <code>repeated .lunarclient.apollo.common.v1.Component.TextDecorator decorators = 3 [json_name = "decorators"];</code>
     * @param index The index of the element to return.
     * @return The decorators at the given index.
     */
    lunarclient.apollo.common.v1.ComponentOuterClass.Component.TextDecorator getDecorators(int index);
    /**
     * <code>repeated .lunarclient.apollo.common.v1.Component.TextDecorator decorators = 3 [json_name = "decorators"];</code>
     * @return A list containing the enum numeric values on the wire for decorators.
     */
    java.util.List<java.lang.Integer>
    getDecoratorsValueList();
    /**
     * <code>repeated .lunarclient.apollo.common.v1.Component.TextDecorator decorators = 3 [json_name = "decorators"];</code>
     * @param index The index of the value to return.
     * @return The enum numeric value on the wire of decorators at the given index.
     */
    int getDecoratorsValue(int index);

    /**
     * <code>repeated .lunarclient.apollo.common.v1.Component children = 4 [json_name = "children"];</code>
     */
    java.util.List<lunarclient.apollo.common.v1.ComponentOuterClass.Component> 
        getChildrenList();
    /**
     * <code>repeated .lunarclient.apollo.common.v1.Component children = 4 [json_name = "children"];</code>
     */
    lunarclient.apollo.common.v1.ComponentOuterClass.Component getChildren(int index);
    /**
     * <code>repeated .lunarclient.apollo.common.v1.Component children = 4 [json_name = "children"];</code>
     */
    int getChildrenCount();
    /**
     * <code>repeated .lunarclient.apollo.common.v1.Component children = 4 [json_name = "children"];</code>
     */
    java.util.List<? extends lunarclient.apollo.common.v1.ComponentOuterClass.ComponentOrBuilder> 
        getChildrenOrBuilderList();
    /**
     * <code>repeated .lunarclient.apollo.common.v1.Component children = 4 [json_name = "children"];</code>
     */
    lunarclient.apollo.common.v1.ComponentOuterClass.ComponentOrBuilder getChildrenOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code lunarclient.apollo.common.v1.Component}
   */
  @java.lang.Deprecated public static final class Component extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:lunarclient.apollo.common.v1.Component)
      ComponentOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 1,
        /* suffix= */ "",
        Component.class.getName());
    }
    // Use Component.newBuilder() to construct.
    private Component(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Component() {
      content_ = "";
      decorators_ = emptyIntList();
      children_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return lunarclient.apollo.common.v1.ComponentOuterClass.internal_static_lunarclient_apollo_common_v1_Component_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return lunarclient.apollo.common.v1.ComponentOuterClass.internal_static_lunarclient_apollo_common_v1_Component_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              lunarclient.apollo.common.v1.ComponentOuterClass.Component.class, lunarclient.apollo.common.v1.ComponentOuterClass.Component.Builder.class);
    }

    /**
     * Protobuf enum {@code lunarclient.apollo.common.v1.Component.TextDecorator}
     */
    public enum TextDecorator
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>TEXT_DECORATOR_UNSPECIFIED = 0;</code>
       */
      TEXT_DECORATOR_UNSPECIFIED(0),
      /**
       * <code>TEXT_DECORATOR_OBFUSCATED = 1;</code>
       */
      TEXT_DECORATOR_OBFUSCATED(1),
      /**
       * <code>TEXT_DECORATOR_BOLD = 2;</code>
       */
      TEXT_DECORATOR_BOLD(2),
      /**
       * <code>TEXT_DECORATOR_STRIKETHROUGH = 3;</code>
       */
      TEXT_DECORATOR_STRIKETHROUGH(3),
      /**
       * <code>TEXT_DECORATOR_UNDERLINED = 4;</code>
       */
      TEXT_DECORATOR_UNDERLINED(4),
      /**
       * <code>TEXT_DECORATOR_ITALIC = 5;</code>
       */
      TEXT_DECORATOR_ITALIC(5),
      UNRECOGNIZED(-1),
      ;

      static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
          com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
          /* major= */ 4,
          /* minor= */ 31,
          /* patch= */ 1,
          /* suffix= */ "",
          TextDecorator.class.getName());
      }
      /**
       * <code>TEXT_DECORATOR_UNSPECIFIED = 0;</code>
       */
      public static final int TEXT_DECORATOR_UNSPECIFIED_VALUE = 0;
      /**
       * <code>TEXT_DECORATOR_OBFUSCATED = 1;</code>
       */
      public static final int TEXT_DECORATOR_OBFUSCATED_VALUE = 1;
      /**
       * <code>TEXT_DECORATOR_BOLD = 2;</code>
       */
      public static final int TEXT_DECORATOR_BOLD_VALUE = 2;
      /**
       * <code>TEXT_DECORATOR_STRIKETHROUGH = 3;</code>
       */
      public static final int TEXT_DECORATOR_STRIKETHROUGH_VALUE = 3;
      /**
       * <code>TEXT_DECORATOR_UNDERLINED = 4;</code>
       */
      public static final int TEXT_DECORATOR_UNDERLINED_VALUE = 4;
      /**
       * <code>TEXT_DECORATOR_ITALIC = 5;</code>
       */
      public static final int TEXT_DECORATOR_ITALIC_VALUE = 5;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static TextDecorator valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static TextDecorator forNumber(int value) {
        switch (value) {
          case 0: return TEXT_DECORATOR_UNSPECIFIED;
          case 1: return TEXT_DECORATOR_OBFUSCATED;
          case 2: return TEXT_DECORATOR_BOLD;
          case 3: return TEXT_DECORATOR_STRIKETHROUGH;
          case 4: return TEXT_DECORATOR_UNDERLINED;
          case 5: return TEXT_DECORATOR_ITALIC;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<TextDecorator>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          TextDecorator> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<TextDecorator>() {
              public TextDecorator findValueByNumber(int number) {
                return TextDecorator.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return lunarclient.apollo.common.v1.ComponentOuterClass.Component.getDescriptor().getEnumTypes().get(0);
      }

      private static final TextDecorator[] VALUES = values();

      public static TextDecorator valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private TextDecorator(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:lunarclient.apollo.common.v1.Component.TextDecorator)
    }

    private int bitField0_;
    public static final int CONTENT_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object content_ = "";
    /**
     * <code>string content = 1 [json_name = "content"];</code>
     * @return The content.
     */
    @java.lang.Override
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <code>string content = 1 [json_name = "content"];</code>
     * @return The bytes for content.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COLOR_FIELD_NUMBER = 2;
    private lunarclient.apollo.common.v1.ColorOuterClass.Color color_;
    /**
     * <code>.lunarclient.apollo.common.v1.Color color = 2 [json_name = "color"];</code>
     * @return Whether the color field is set.
     */
    @java.lang.Override
    public boolean hasColor() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.lunarclient.apollo.common.v1.Color color = 2 [json_name = "color"];</code>
     * @return The color.
     */
    @java.lang.Override
    public lunarclient.apollo.common.v1.ColorOuterClass.Color getColor() {
      return color_ == null ? lunarclient.apollo.common.v1.ColorOuterClass.Color.getDefaultInstance() : color_;
    }
    /**
     * <code>.lunarclient.apollo.common.v1.Color color = 2 [json_name = "color"];</code>
     */
    @java.lang.Override
    public lunarclient.apollo.common.v1.ColorOuterClass.ColorOrBuilder getColorOrBuilder() {
      return color_ == null ? lunarclient.apollo.common.v1.ColorOuterClass.Color.getDefaultInstance() : color_;
    }

    public static final int DECORATORS_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private com.google.protobuf.Internal.IntList decorators_ =
        emptyIntList();
    private static final     com.google.protobuf.Internal.IntListAdapter.IntConverter<
        lunarclient.apollo.common.v1.ComponentOuterClass.Component.TextDecorator> decorators_converter_ =
            new com.google.protobuf.Internal.IntListAdapter.IntConverter<
                lunarclient.apollo.common.v1.ComponentOuterClass.Component.TextDecorator>() {
              public lunarclient.apollo.common.v1.ComponentOuterClass.Component.TextDecorator convert(int from) {
                lunarclient.apollo.common.v1.ComponentOuterClass.Component.TextDecorator result = lunarclient.apollo.common.v1.ComponentOuterClass.Component.TextDecorator.forNumber(from);
                return result == null ? lunarclient.apollo.common.v1.ComponentOuterClass.Component.TextDecorator.UNRECOGNIZED : result;
              }
            };
    /**
     * <code>repeated .lunarclient.apollo.common.v1.Component.TextDecorator decorators = 3 [json_name = "decorators"];</code>
     * @return A list containing the decorators.
     */
    @java.lang.Override
    public java.util.List<lunarclient.apollo.common.v1.ComponentOuterClass.Component.TextDecorator> getDecoratorsList() {
      return new com.google.protobuf.Internal.IntListAdapter<
          lunarclient.apollo.common.v1.ComponentOuterClass.Component.TextDecorator>(decorators_, decorators_converter_);
    }
    /**
     * <code>repeated .lunarclient.apollo.common.v1.Component.TextDecorator decorators = 3 [json_name = "decorators"];</code>
     * @return The count of decorators.
     */
    @java.lang.Override
    public int getDecoratorsCount() {
      return decorators_.size();
    }
    /**
     * <code>repeated .lunarclient.apollo.common.v1.Component.TextDecorator decorators = 3 [json_name = "decorators"];</code>
     * @param index The index of the element to return.
     * @return The decorators at the given index.
     */
    @java.lang.Override
    public lunarclient.apollo.common.v1.ComponentOuterClass.Component.TextDecorator getDecorators(int index) {
      return decorators_converter_.convert(decorators_.getInt(index));
    }
    /**
     * <code>repeated .lunarclient.apollo.common.v1.Component.TextDecorator decorators = 3 [json_name = "decorators"];</code>
     * @return A list containing the enum numeric values on the wire for decorators.
     */
    @java.lang.Override
    public java.util.List<java.lang.Integer>
    getDecoratorsValueList() {
      return decorators_;
    }
    /**
     * <code>repeated .lunarclient.apollo.common.v1.Component.TextDecorator decorators = 3 [json_name = "decorators"];</code>
     * @param index The index of the value to return.
     * @return The enum numeric value on the wire of decorators at the given index.
     */
    @java.lang.Override
    public int getDecoratorsValue(int index) {
      return decorators_.getInt(index);
    }
    private int decoratorsMemoizedSerializedSize;

    public static final int CHILDREN_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private java.util.List<lunarclient.apollo.common.v1.ComponentOuterClass.Component> children_;
    /**
     * <code>repeated .lunarclient.apollo.common.v1.Component children = 4 [json_name = "children"];</code>
     */
    @java.lang.Override
    public java.util.List<lunarclient.apollo.common.v1.ComponentOuterClass.Component> getChildrenList() {
      return children_;
    }
    /**
     * <code>repeated .lunarclient.apollo.common.v1.Component children = 4 [json_name = "children"];</code>
     */
    @java.lang.Override
    public java.util.List<? extends lunarclient.apollo.common.v1.ComponentOuterClass.ComponentOrBuilder> 
        getChildrenOrBuilderList() {
      return children_;
    }
    /**
     * <code>repeated .lunarclient.apollo.common.v1.Component children = 4 [json_name = "children"];</code>
     */
    @java.lang.Override
    public int getChildrenCount() {
      return children_.size();
    }
    /**
     * <code>repeated .lunarclient.apollo.common.v1.Component children = 4 [json_name = "children"];</code>
     */
    @java.lang.Override
    public lunarclient.apollo.common.v1.ComponentOuterClass.Component getChildren(int index) {
      return children_.get(index);
    }
    /**
     * <code>repeated .lunarclient.apollo.common.v1.Component children = 4 [json_name = "children"];</code>
     */
    @java.lang.Override
    public lunarclient.apollo.common.v1.ComponentOuterClass.ComponentOrBuilder getChildrenOrBuilder(
        int index) {
      return children_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(content_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, content_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(2, getColor());
      }
      if (getDecoratorsList().size() > 0) {
        output.writeUInt32NoTag(26);
        output.writeUInt32NoTag(decoratorsMemoizedSerializedSize);
      }
      for (int i = 0; i < decorators_.size(); i++) {
        output.writeEnumNoTag(decorators_.getInt(i));
      }
      for (int i = 0; i < children_.size(); i++) {
        output.writeMessage(4, children_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(content_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, content_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getColor());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < decorators_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeEnumSizeNoTag(decorators_.getInt(i));
        }
        size += dataSize;
        if (!getDecoratorsList().isEmpty()) {  size += 1;
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32SizeNoTag(dataSize);
        }decoratorsMemoizedSerializedSize = dataSize;
      }
      for (int i = 0; i < children_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, children_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof lunarclient.apollo.common.v1.ComponentOuterClass.Component)) {
        return super.equals(obj);
      }
      lunarclient.apollo.common.v1.ComponentOuterClass.Component other = (lunarclient.apollo.common.v1.ComponentOuterClass.Component) obj;

      if (!getContent()
          .equals(other.getContent())) return false;
      if (hasColor() != other.hasColor()) return false;
      if (hasColor()) {
        if (!getColor()
            .equals(other.getColor())) return false;
      }
      if (!decorators_.equals(other.decorators_)) return false;
      if (!getChildrenList()
          .equals(other.getChildrenList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      if (hasColor()) {
        hash = (37 * hash) + COLOR_FIELD_NUMBER;
        hash = (53 * hash) + getColor().hashCode();
      }
      if (getDecoratorsCount() > 0) {
        hash = (37 * hash) + DECORATORS_FIELD_NUMBER;
        hash = (53 * hash) + decorators_.hashCode();
      }
      if (getChildrenCount() > 0) {
        hash = (37 * hash) + CHILDREN_FIELD_NUMBER;
        hash = (53 * hash) + getChildrenList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static lunarclient.apollo.common.v1.ComponentOuterClass.Component parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lunarclient.apollo.common.v1.ComponentOuterClass.Component parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lunarclient.apollo.common.v1.ComponentOuterClass.Component parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lunarclient.apollo.common.v1.ComponentOuterClass.Component parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lunarclient.apollo.common.v1.ComponentOuterClass.Component parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lunarclient.apollo.common.v1.ComponentOuterClass.Component parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lunarclient.apollo.common.v1.ComponentOuterClass.Component parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static lunarclient.apollo.common.v1.ComponentOuterClass.Component parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static lunarclient.apollo.common.v1.ComponentOuterClass.Component parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static lunarclient.apollo.common.v1.ComponentOuterClass.Component parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static lunarclient.apollo.common.v1.ComponentOuterClass.Component parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static lunarclient.apollo.common.v1.ComponentOuterClass.Component parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(lunarclient.apollo.common.v1.ComponentOuterClass.Component prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code lunarclient.apollo.common.v1.Component}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:lunarclient.apollo.common.v1.Component)
        lunarclient.apollo.common.v1.ComponentOuterClass.ComponentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return lunarclient.apollo.common.v1.ComponentOuterClass.internal_static_lunarclient_apollo_common_v1_Component_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return lunarclient.apollo.common.v1.ComponentOuterClass.internal_static_lunarclient_apollo_common_v1_Component_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                lunarclient.apollo.common.v1.ComponentOuterClass.Component.class, lunarclient.apollo.common.v1.ComponentOuterClass.Component.Builder.class);
      }

      // Construct using lunarclient.apollo.common.v1.ComponentOuterClass.Component.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          internalGetColorFieldBuilder();
          internalGetChildrenFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        content_ = "";
        color_ = null;
        if (colorBuilder_ != null) {
          colorBuilder_.dispose();
          colorBuilder_ = null;
        }
        decorators_ = emptyIntList();
        if (childrenBuilder_ == null) {
          children_ = java.util.Collections.emptyList();
        } else {
          children_ = null;
          childrenBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return lunarclient.apollo.common.v1.ComponentOuterClass.internal_static_lunarclient_apollo_common_v1_Component_descriptor;
      }

      @java.lang.Override
      public lunarclient.apollo.common.v1.ComponentOuterClass.Component getDefaultInstanceForType() {
        return lunarclient.apollo.common.v1.ComponentOuterClass.Component.getDefaultInstance();
      }

      @java.lang.Override
      public lunarclient.apollo.common.v1.ComponentOuterClass.Component build() {
        lunarclient.apollo.common.v1.ComponentOuterClass.Component result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public lunarclient.apollo.common.v1.ComponentOuterClass.Component buildPartial() {
        lunarclient.apollo.common.v1.ComponentOuterClass.Component result = new lunarclient.apollo.common.v1.ComponentOuterClass.Component(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(lunarclient.apollo.common.v1.ComponentOuterClass.Component result) {
        if (childrenBuilder_ == null) {
          if (((bitField0_ & 0x00000008) != 0)) {
            children_ = java.util.Collections.unmodifiableList(children_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.children_ = children_;
        } else {
          result.children_ = childrenBuilder_.build();
        }
      }

      private void buildPartial0(lunarclient.apollo.common.v1.ComponentOuterClass.Component result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.content_ = content_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.color_ = colorBuilder_ == null
              ? color_
              : colorBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          decorators_.makeImmutable();
          result.decorators_ = decorators_;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof lunarclient.apollo.common.v1.ComponentOuterClass.Component) {
          return mergeFrom((lunarclient.apollo.common.v1.ComponentOuterClass.Component)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(lunarclient.apollo.common.v1.ComponentOuterClass.Component other) {
        if (other == lunarclient.apollo.common.v1.ComponentOuterClass.Component.getDefaultInstance()) return this;
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.hasColor()) {
          mergeColor(other.getColor());
        }
        if (!other.decorators_.isEmpty()) {
          if (decorators_.isEmpty()) {
            decorators_ = other.decorators_;
            decorators_.makeImmutable();
            bitField0_ |= 0x00000004;
          } else {
            ensureDecoratorsIsMutable();
            decorators_.addAll(other.decorators_);
          }
          onChanged();
        }
        if (childrenBuilder_ == null) {
          if (!other.children_.isEmpty()) {
            if (children_.isEmpty()) {
              children_ = other.children_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureChildrenIsMutable();
              children_.addAll(other.children_);
            }
            onChanged();
          }
        } else {
          if (!other.children_.isEmpty()) {
            if (childrenBuilder_.isEmpty()) {
              childrenBuilder_.dispose();
              childrenBuilder_ = null;
              children_ = other.children_;
              bitField0_ = (bitField0_ & ~0x00000008);
              childrenBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   internalGetChildrenFieldBuilder() : null;
            } else {
              childrenBuilder_.addAllMessages(other.children_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                content_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                input.readMessage(
                    internalGetColorFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                int tmpRaw = input.readEnum();
                ensureDecoratorsIsMutable();
                decorators_.addInt(tmpRaw);
                break;
              } // case 24
              case 26: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                ensureDecoratorsIsMutable();
                while (input.getBytesUntilLimit() > 0) {
                  decorators_.addInt(input.readEnum());
                }
                input.popLimit(limit);
                break;
              } // case 26
              case 34: {
                lunarclient.apollo.common.v1.ComponentOuterClass.Component m =
                    input.readMessage(
                        lunarclient.apollo.common.v1.ComponentOuterClass.Component.parser(),
                        extensionRegistry);
                if (childrenBuilder_ == null) {
                  ensureChildrenIsMutable();
                  children_.add(m);
                } else {
                  childrenBuilder_.addMessage(m);
                }
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object content_ = "";
      /**
       * <code>string content = 1 [json_name = "content"];</code>
       * @return The content.
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string content = 1 [json_name = "content"];</code>
       * @return The bytes for content.
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string content = 1 [json_name = "content"];</code>
       * @param value The content to set.
       * @return This builder for chaining.
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        content_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string content = 1 [json_name = "content"];</code>
       * @return This builder for chaining.
       */
      public Builder clearContent() {
        content_ = getDefaultInstance().getContent();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string content = 1 [json_name = "content"];</code>
       * @param value The bytes for content to set.
       * @return This builder for chaining.
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        content_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private lunarclient.apollo.common.v1.ColorOuterClass.Color color_;
      private com.google.protobuf.SingleFieldBuilder<
          lunarclient.apollo.common.v1.ColorOuterClass.Color, lunarclient.apollo.common.v1.ColorOuterClass.Color.Builder, lunarclient.apollo.common.v1.ColorOuterClass.ColorOrBuilder> colorBuilder_;
      /**
       * <code>.lunarclient.apollo.common.v1.Color color = 2 [json_name = "color"];</code>
       * @return Whether the color field is set.
       */
      public boolean hasColor() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>.lunarclient.apollo.common.v1.Color color = 2 [json_name = "color"];</code>
       * @return The color.
       */
      public lunarclient.apollo.common.v1.ColorOuterClass.Color getColor() {
        if (colorBuilder_ == null) {
          return color_ == null ? lunarclient.apollo.common.v1.ColorOuterClass.Color.getDefaultInstance() : color_;
        } else {
          return colorBuilder_.getMessage();
        }
      }
      /**
       * <code>.lunarclient.apollo.common.v1.Color color = 2 [json_name = "color"];</code>
       */
      public Builder setColor(lunarclient.apollo.common.v1.ColorOuterClass.Color value) {
        if (colorBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          color_ = value;
        } else {
          colorBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.lunarclient.apollo.common.v1.Color color = 2 [json_name = "color"];</code>
       */
      public Builder setColor(
          lunarclient.apollo.common.v1.ColorOuterClass.Color.Builder builderForValue) {
        if (colorBuilder_ == null) {
          color_ = builderForValue.build();
        } else {
          colorBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.lunarclient.apollo.common.v1.Color color = 2 [json_name = "color"];</code>
       */
      public Builder mergeColor(lunarclient.apollo.common.v1.ColorOuterClass.Color value) {
        if (colorBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            color_ != null &&
            color_ != lunarclient.apollo.common.v1.ColorOuterClass.Color.getDefaultInstance()) {
            getColorBuilder().mergeFrom(value);
          } else {
            color_ = value;
          }
        } else {
          colorBuilder_.mergeFrom(value);
        }
        if (color_ != null) {
          bitField0_ |= 0x00000002;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.lunarclient.apollo.common.v1.Color color = 2 [json_name = "color"];</code>
       */
      public Builder clearColor() {
        bitField0_ = (bitField0_ & ~0x00000002);
        color_ = null;
        if (colorBuilder_ != null) {
          colorBuilder_.dispose();
          colorBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.lunarclient.apollo.common.v1.Color color = 2 [json_name = "color"];</code>
       */
      public lunarclient.apollo.common.v1.ColorOuterClass.Color.Builder getColorBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return internalGetColorFieldBuilder().getBuilder();
      }
      /**
       * <code>.lunarclient.apollo.common.v1.Color color = 2 [json_name = "color"];</code>
       */
      public lunarclient.apollo.common.v1.ColorOuterClass.ColorOrBuilder getColorOrBuilder() {
        if (colorBuilder_ != null) {
          return colorBuilder_.getMessageOrBuilder();
        } else {
          return color_ == null ?
              lunarclient.apollo.common.v1.ColorOuterClass.Color.getDefaultInstance() : color_;
        }
      }
      /**
       * <code>.lunarclient.apollo.common.v1.Color color = 2 [json_name = "color"];</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          lunarclient.apollo.common.v1.ColorOuterClass.Color, lunarclient.apollo.common.v1.ColorOuterClass.Color.Builder, lunarclient.apollo.common.v1.ColorOuterClass.ColorOrBuilder> 
          internalGetColorFieldBuilder() {
        if (colorBuilder_ == null) {
          colorBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              lunarclient.apollo.common.v1.ColorOuterClass.Color, lunarclient.apollo.common.v1.ColorOuterClass.Color.Builder, lunarclient.apollo.common.v1.ColorOuterClass.ColorOrBuilder>(
                  getColor(),
                  getParentForChildren(),
                  isClean());
          color_ = null;
        }
        return colorBuilder_;
      }

      private com.google.protobuf.Internal.IntList decorators_ = emptyIntList();
      private void ensureDecoratorsIsMutable() {
        if (!decorators_.isModifiable()) {
          decorators_ = makeMutableCopy(decorators_);
        }
        bitField0_ |= 0x00000004;
      }
      /**
       * <code>repeated .lunarclient.apollo.common.v1.Component.TextDecorator decorators = 3 [json_name = "decorators"];</code>
       * @return A list containing the decorators.
       */
      public java.util.List<lunarclient.apollo.common.v1.ComponentOuterClass.Component.TextDecorator> getDecoratorsList() {
        return new com.google.protobuf.Internal.IntListAdapter<
            lunarclient.apollo.common.v1.ComponentOuterClass.Component.TextDecorator>(decorators_, decorators_converter_);
      }
      /**
       * <code>repeated .lunarclient.apollo.common.v1.Component.TextDecorator decorators = 3 [json_name = "decorators"];</code>
       * @return The count of decorators.
       */
      public int getDecoratorsCount() {
        return decorators_.size();
      }
      /**
       * <code>repeated .lunarclient.apollo.common.v1.Component.TextDecorator decorators = 3 [json_name = "decorators"];</code>
       * @param index The index of the element to return.
       * @return The decorators at the given index.
       */
      public lunarclient.apollo.common.v1.ComponentOuterClass.Component.TextDecorator getDecorators(int index) {
        return decorators_converter_.convert(decorators_.getInt(index));
      }
      /**
       * <code>repeated .lunarclient.apollo.common.v1.Component.TextDecorator decorators = 3 [json_name = "decorators"];</code>
       * @param index The index to set the value at.
       * @param value The decorators to set.
       * @return This builder for chaining.
       */
      public Builder setDecorators(
          int index, lunarclient.apollo.common.v1.ComponentOuterClass.Component.TextDecorator value) {
        if (value == null) { throw new NullPointerException(); }
        ensureDecoratorsIsMutable();
        decorators_.setInt(index, value.getNumber());
        onChanged();
        return this;
      }
      /**
       * <code>repeated .lunarclient.apollo.common.v1.Component.TextDecorator decorators = 3 [json_name = "decorators"];</code>
       * @param value The decorators to add.
       * @return This builder for chaining.
       */
      public Builder addDecorators(lunarclient.apollo.common.v1.ComponentOuterClass.Component.TextDecorator value) {
        if (value == null) { throw new NullPointerException(); }
        ensureDecoratorsIsMutable();
        decorators_.addInt(value.getNumber());
        onChanged();
        return this;
      }
      /**
       * <code>repeated .lunarclient.apollo.common.v1.Component.TextDecorator decorators = 3 [json_name = "decorators"];</code>
       * @param values The decorators to add.
       * @return This builder for chaining.
       */
      public Builder addAllDecorators(
          java.lang.Iterable<? extends lunarclient.apollo.common.v1.ComponentOuterClass.Component.TextDecorator> values) {
        ensureDecoratorsIsMutable();
        for (lunarclient.apollo.common.v1.ComponentOuterClass.Component.TextDecorator value : values) {
          decorators_.addInt(value.getNumber());
        }
        onChanged();
        return this;
      }
      /**
       * <code>repeated .lunarclient.apollo.common.v1.Component.TextDecorator decorators = 3 [json_name = "decorators"];</code>
       * @return This builder for chaining.
       */
      public Builder clearDecorators() {
        decorators_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .lunarclient.apollo.common.v1.Component.TextDecorator decorators = 3 [json_name = "decorators"];</code>
       * @return A list containing the enum numeric values on the wire for decorators.
       */
      public java.util.List<java.lang.Integer>
      getDecoratorsValueList() {
        decorators_.makeImmutable();
        return decorators_;
      }
      /**
       * <code>repeated .lunarclient.apollo.common.v1.Component.TextDecorator decorators = 3 [json_name = "decorators"];</code>
       * @param index The index of the value to return.
       * @return The enum numeric value on the wire of decorators at the given index.
       */
      public int getDecoratorsValue(int index) {
        return decorators_.getInt(index);
      }
      /**
       * <code>repeated .lunarclient.apollo.common.v1.Component.TextDecorator decorators = 3 [json_name = "decorators"];</code>
       * @param index The index to set the value at.
       * @param value The enum numeric value on the wire for decorators to set.
       * @return This builder for chaining.
       */
      public Builder setDecoratorsValue(
          int index, int value) {
        ensureDecoratorsIsMutable();
        decorators_.setInt(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .lunarclient.apollo.common.v1.Component.TextDecorator decorators = 3 [json_name = "decorators"];</code>
       * @param value The enum numeric value on the wire for decorators to add.
       * @return This builder for chaining.
       */
      public Builder addDecoratorsValue(int value) {
        ensureDecoratorsIsMutable();
        decorators_.addInt(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .lunarclient.apollo.common.v1.Component.TextDecorator decorators = 3 [json_name = "decorators"];</code>
       * @param values The enum numeric values on the wire for decorators to add.
       * @return This builder for chaining.
       */
      public Builder addAllDecoratorsValue(
          java.lang.Iterable<java.lang.Integer> values) {
        ensureDecoratorsIsMutable();
        for (int value : values) {
          decorators_.addInt(value);
        }
        onChanged();
        return this;
      }

      private java.util.List<lunarclient.apollo.common.v1.ComponentOuterClass.Component> children_ =
        java.util.Collections.emptyList();
      private void ensureChildrenIsMutable() {
        if (!((bitField0_ & 0x00000008) != 0)) {
          children_ = new java.util.ArrayList<lunarclient.apollo.common.v1.ComponentOuterClass.Component>(children_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          lunarclient.apollo.common.v1.ComponentOuterClass.Component, lunarclient.apollo.common.v1.ComponentOuterClass.Component.Builder, lunarclient.apollo.common.v1.ComponentOuterClass.ComponentOrBuilder> childrenBuilder_;

      /**
       * <code>repeated .lunarclient.apollo.common.v1.Component children = 4 [json_name = "children"];</code>
       */
      public java.util.List<lunarclient.apollo.common.v1.ComponentOuterClass.Component> getChildrenList() {
        if (childrenBuilder_ == null) {
          return java.util.Collections.unmodifiableList(children_);
        } else {
          return childrenBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .lunarclient.apollo.common.v1.Component children = 4 [json_name = "children"];</code>
       */
      public int getChildrenCount() {
        if (childrenBuilder_ == null) {
          return children_.size();
        } else {
          return childrenBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .lunarclient.apollo.common.v1.Component children = 4 [json_name = "children"];</code>
       */
      public lunarclient.apollo.common.v1.ComponentOuterClass.Component getChildren(int index) {
        if (childrenBuilder_ == null) {
          return children_.get(index);
        } else {
          return childrenBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .lunarclient.apollo.common.v1.Component children = 4 [json_name = "children"];</code>
       */
      public Builder setChildren(
          int index, lunarclient.apollo.common.v1.ComponentOuterClass.Component value) {
        if (childrenBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureChildrenIsMutable();
          children_.set(index, value);
          onChanged();
        } else {
          childrenBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .lunarclient.apollo.common.v1.Component children = 4 [json_name = "children"];</code>
       */
      public Builder setChildren(
          int index, lunarclient.apollo.common.v1.ComponentOuterClass.Component.Builder builderForValue) {
        if (childrenBuilder_ == null) {
          ensureChildrenIsMutable();
          children_.set(index, builderForValue.build());
          onChanged();
        } else {
          childrenBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .lunarclient.apollo.common.v1.Component children = 4 [json_name = "children"];</code>
       */
      public Builder addChildren(lunarclient.apollo.common.v1.ComponentOuterClass.Component value) {
        if (childrenBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureChildrenIsMutable();
          children_.add(value);
          onChanged();
        } else {
          childrenBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .lunarclient.apollo.common.v1.Component children = 4 [json_name = "children"];</code>
       */
      public Builder addChildren(
          int index, lunarclient.apollo.common.v1.ComponentOuterClass.Component value) {
        if (childrenBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureChildrenIsMutable();
          children_.add(index, value);
          onChanged();
        } else {
          childrenBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .lunarclient.apollo.common.v1.Component children = 4 [json_name = "children"];</code>
       */
      public Builder addChildren(
          lunarclient.apollo.common.v1.ComponentOuterClass.Component.Builder builderForValue) {
        if (childrenBuilder_ == null) {
          ensureChildrenIsMutable();
          children_.add(builderForValue.build());
          onChanged();
        } else {
          childrenBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .lunarclient.apollo.common.v1.Component children = 4 [json_name = "children"];</code>
       */
      public Builder addChildren(
          int index, lunarclient.apollo.common.v1.ComponentOuterClass.Component.Builder builderForValue) {
        if (childrenBuilder_ == null) {
          ensureChildrenIsMutable();
          children_.add(index, builderForValue.build());
          onChanged();
        } else {
          childrenBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .lunarclient.apollo.common.v1.Component children = 4 [json_name = "children"];</code>
       */
      public Builder addAllChildren(
          java.lang.Iterable<? extends lunarclient.apollo.common.v1.ComponentOuterClass.Component> values) {
        if (childrenBuilder_ == null) {
          ensureChildrenIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, children_);
          onChanged();
        } else {
          childrenBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .lunarclient.apollo.common.v1.Component children = 4 [json_name = "children"];</code>
       */
      public Builder clearChildren() {
        if (childrenBuilder_ == null) {
          children_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          childrenBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .lunarclient.apollo.common.v1.Component children = 4 [json_name = "children"];</code>
       */
      public Builder removeChildren(int index) {
        if (childrenBuilder_ == null) {
          ensureChildrenIsMutable();
          children_.remove(index);
          onChanged();
        } else {
          childrenBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .lunarclient.apollo.common.v1.Component children = 4 [json_name = "children"];</code>
       */
      public lunarclient.apollo.common.v1.ComponentOuterClass.Component.Builder getChildrenBuilder(
          int index) {
        return internalGetChildrenFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .lunarclient.apollo.common.v1.Component children = 4 [json_name = "children"];</code>
       */
      public lunarclient.apollo.common.v1.ComponentOuterClass.ComponentOrBuilder getChildrenOrBuilder(
          int index) {
        if (childrenBuilder_ == null) {
          return children_.get(index);  } else {
          return childrenBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .lunarclient.apollo.common.v1.Component children = 4 [json_name = "children"];</code>
       */
      public java.util.List<? extends lunarclient.apollo.common.v1.ComponentOuterClass.ComponentOrBuilder> 
           getChildrenOrBuilderList() {
        if (childrenBuilder_ != null) {
          return childrenBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(children_);
        }
      }
      /**
       * <code>repeated .lunarclient.apollo.common.v1.Component children = 4 [json_name = "children"];</code>
       */
      public lunarclient.apollo.common.v1.ComponentOuterClass.Component.Builder addChildrenBuilder() {
        return internalGetChildrenFieldBuilder().addBuilder(
            lunarclient.apollo.common.v1.ComponentOuterClass.Component.getDefaultInstance());
      }
      /**
       * <code>repeated .lunarclient.apollo.common.v1.Component children = 4 [json_name = "children"];</code>
       */
      public lunarclient.apollo.common.v1.ComponentOuterClass.Component.Builder addChildrenBuilder(
          int index) {
        return internalGetChildrenFieldBuilder().addBuilder(
            index, lunarclient.apollo.common.v1.ComponentOuterClass.Component.getDefaultInstance());
      }
      /**
       * <code>repeated .lunarclient.apollo.common.v1.Component children = 4 [json_name = "children"];</code>
       */
      public java.util.List<lunarclient.apollo.common.v1.ComponentOuterClass.Component.Builder> 
           getChildrenBuilderList() {
        return internalGetChildrenFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          lunarclient.apollo.common.v1.ComponentOuterClass.Component, lunarclient.apollo.common.v1.ComponentOuterClass.Component.Builder, lunarclient.apollo.common.v1.ComponentOuterClass.ComponentOrBuilder> 
          internalGetChildrenFieldBuilder() {
        if (childrenBuilder_ == null) {
          childrenBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              lunarclient.apollo.common.v1.ComponentOuterClass.Component, lunarclient.apollo.common.v1.ComponentOuterClass.Component.Builder, lunarclient.apollo.common.v1.ComponentOuterClass.ComponentOrBuilder>(
                  children_,
                  ((bitField0_ & 0x00000008) != 0),
                  getParentForChildren(),
                  isClean());
          children_ = null;
        }
        return childrenBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:lunarclient.apollo.common.v1.Component)
    }

    // @@protoc_insertion_point(class_scope:lunarclient.apollo.common.v1.Component)
    private static final lunarclient.apollo.common.v1.ComponentOuterClass.Component DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new lunarclient.apollo.common.v1.ComponentOuterClass.Component();
    }

    public static lunarclient.apollo.common.v1.ComponentOuterClass.Component getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Component>
        PARSER = new com.google.protobuf.AbstractParser<Component>() {
      @java.lang.Override
      public Component parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Component> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Component> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public lunarclient.apollo.common.v1.ComponentOuterClass.Component getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lunarclient_apollo_common_v1_Component_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lunarclient_apollo_common_v1_Component_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n,lunarclient/apollo/common/v1/component" +
      ".proto\022\034lunarclient.apollo.common.v1\032(lu" +
      "narclient/apollo/common/v1/color.proto\"\306" +
      "\003\n\tComponent\022\030\n\007content\030\001 \001(\tR\007content\0229" +
      "\n\005color\030\002 \001(\0132#.lunarclient.apollo.commo" +
      "n.v1.ColorR\005color\022U\n\ndecorators\030\003 \003(\01625." +
      "lunarclient.apollo.common.v1.Component.T" +
      "extDecoratorR\ndecorators\022C\n\010children\030\004 \003" +
      "(\0132\'.lunarclient.apollo.common.v1.Compon" +
      "entR\010children\"\303\001\n\rTextDecorator\022\036\n\032TEXT_" +
      "DECORATOR_UNSPECIFIED\020\000\022\035\n\031TEXT_DECORATO" +
      "R_OBFUSCATED\020\001\022\027\n\023TEXT_DECORATOR_BOLD\020\002\022" +
      " \n\034TEXT_DECORATOR_STRIKETHROUGH\020\003\022\035\n\031TEX" +
      "T_DECORATOR_UNDERLINED\020\004\022\031\n\025TEXT_DECORAT" +
      "OR_ITALIC\020\005:\002\030\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          lunarclient.apollo.common.v1.ColorOuterClass.getDescriptor(),
        });
    internal_static_lunarclient_apollo_common_v1_Component_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_lunarclient_apollo_common_v1_Component_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lunarclient_apollo_common_v1_Component_descriptor,
        new java.lang.String[] { "Content", "Color", "Decorators", "Children", });
    descriptor.resolveAllFeaturesImmutable();
    lunarclient.apollo.common.v1.ColorOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
