// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: lunarclient/apollo/common/v1/cuboid.proto
// Protobuf Java Version: 4.31.1

package lunarclient.apollo.common.v1;

@com.google.protobuf.Generated
public final class Cuboid {
  private Cuboid() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      Cuboid.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface Cuboid2DOrBuilder extends
      // @@protoc_insertion_point(interface_extends:lunarclient.apollo.common.v1.Cuboid2D)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>double min_x = 1 [json_name = "minX"];</code>
     * @return The minX.
     */
    double getMinX();

    /**
     * <code>double min_z = 2 [json_name = "minZ"];</code>
     * @return The minZ.
     */
    double getMinZ();

    /**
     * <code>double max_x = 3 [json_name = "maxX"];</code>
     * @return The maxX.
     */
    double getMaxX();

    /**
     * <code>double max_z = 4 [json_name = "maxZ"];</code>
     * @return The maxZ.
     */
    double getMaxZ();
  }
  /**
   * Protobuf type {@code lunarclient.apollo.common.v1.Cuboid2D}
   */
  public static final class Cuboid2D extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:lunarclient.apollo.common.v1.Cuboid2D)
      Cuboid2DOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 1,
        /* suffix= */ "",
        Cuboid2D.class.getName());
    }
    // Use Cuboid2D.newBuilder() to construct.
    private Cuboid2D(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Cuboid2D() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return lunarclient.apollo.common.v1.Cuboid.internal_static_lunarclient_apollo_common_v1_Cuboid2D_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return lunarclient.apollo.common.v1.Cuboid.internal_static_lunarclient_apollo_common_v1_Cuboid2D_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              lunarclient.apollo.common.v1.Cuboid.Cuboid2D.class, lunarclient.apollo.common.v1.Cuboid.Cuboid2D.Builder.class);
    }

    public static final int MIN_X_FIELD_NUMBER = 1;
    private double minX_ = 0D;
    /**
     * <code>double min_x = 1 [json_name = "minX"];</code>
     * @return The minX.
     */
    @java.lang.Override
    public double getMinX() {
      return minX_;
    }

    public static final int MIN_Z_FIELD_NUMBER = 2;
    private double minZ_ = 0D;
    /**
     * <code>double min_z = 2 [json_name = "minZ"];</code>
     * @return The minZ.
     */
    @java.lang.Override
    public double getMinZ() {
      return minZ_;
    }

    public static final int MAX_X_FIELD_NUMBER = 3;
    private double maxX_ = 0D;
    /**
     * <code>double max_x = 3 [json_name = "maxX"];</code>
     * @return The maxX.
     */
    @java.lang.Override
    public double getMaxX() {
      return maxX_;
    }

    public static final int MAX_Z_FIELD_NUMBER = 4;
    private double maxZ_ = 0D;
    /**
     * <code>double max_z = 4 [json_name = "maxZ"];</code>
     * @return The maxZ.
     */
    @java.lang.Override
    public double getMaxZ() {
      return maxZ_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (java.lang.Double.doubleToRawLongBits(minX_) != 0) {
        output.writeDouble(1, minX_);
      }
      if (java.lang.Double.doubleToRawLongBits(minZ_) != 0) {
        output.writeDouble(2, minZ_);
      }
      if (java.lang.Double.doubleToRawLongBits(maxX_) != 0) {
        output.writeDouble(3, maxX_);
      }
      if (java.lang.Double.doubleToRawLongBits(maxZ_) != 0) {
        output.writeDouble(4, maxZ_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (java.lang.Double.doubleToRawLongBits(minX_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, minX_);
      }
      if (java.lang.Double.doubleToRawLongBits(minZ_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, minZ_);
      }
      if (java.lang.Double.doubleToRawLongBits(maxX_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, maxX_);
      }
      if (java.lang.Double.doubleToRawLongBits(maxZ_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, maxZ_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof lunarclient.apollo.common.v1.Cuboid.Cuboid2D)) {
        return super.equals(obj);
      }
      lunarclient.apollo.common.v1.Cuboid.Cuboid2D other = (lunarclient.apollo.common.v1.Cuboid.Cuboid2D) obj;

      if (java.lang.Double.doubleToLongBits(getMinX())
          != java.lang.Double.doubleToLongBits(
              other.getMinX())) return false;
      if (java.lang.Double.doubleToLongBits(getMinZ())
          != java.lang.Double.doubleToLongBits(
              other.getMinZ())) return false;
      if (java.lang.Double.doubleToLongBits(getMaxX())
          != java.lang.Double.doubleToLongBits(
              other.getMaxX())) return false;
      if (java.lang.Double.doubleToLongBits(getMaxZ())
          != java.lang.Double.doubleToLongBits(
              other.getMaxZ())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MIN_X_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getMinX()));
      hash = (37 * hash) + MIN_Z_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getMinZ()));
      hash = (37 * hash) + MAX_X_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getMaxX()));
      hash = (37 * hash) + MAX_Z_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getMaxZ()));
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static lunarclient.apollo.common.v1.Cuboid.Cuboid2D parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lunarclient.apollo.common.v1.Cuboid.Cuboid2D parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lunarclient.apollo.common.v1.Cuboid.Cuboid2D parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lunarclient.apollo.common.v1.Cuboid.Cuboid2D parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lunarclient.apollo.common.v1.Cuboid.Cuboid2D parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lunarclient.apollo.common.v1.Cuboid.Cuboid2D parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lunarclient.apollo.common.v1.Cuboid.Cuboid2D parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static lunarclient.apollo.common.v1.Cuboid.Cuboid2D parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static lunarclient.apollo.common.v1.Cuboid.Cuboid2D parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static lunarclient.apollo.common.v1.Cuboid.Cuboid2D parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static lunarclient.apollo.common.v1.Cuboid.Cuboid2D parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static lunarclient.apollo.common.v1.Cuboid.Cuboid2D parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(lunarclient.apollo.common.v1.Cuboid.Cuboid2D prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code lunarclient.apollo.common.v1.Cuboid2D}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:lunarclient.apollo.common.v1.Cuboid2D)
        lunarclient.apollo.common.v1.Cuboid.Cuboid2DOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return lunarclient.apollo.common.v1.Cuboid.internal_static_lunarclient_apollo_common_v1_Cuboid2D_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return lunarclient.apollo.common.v1.Cuboid.internal_static_lunarclient_apollo_common_v1_Cuboid2D_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                lunarclient.apollo.common.v1.Cuboid.Cuboid2D.class, lunarclient.apollo.common.v1.Cuboid.Cuboid2D.Builder.class);
      }

      // Construct using lunarclient.apollo.common.v1.Cuboid.Cuboid2D.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        minX_ = 0D;
        minZ_ = 0D;
        maxX_ = 0D;
        maxZ_ = 0D;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return lunarclient.apollo.common.v1.Cuboid.internal_static_lunarclient_apollo_common_v1_Cuboid2D_descriptor;
      }

      @java.lang.Override
      public lunarclient.apollo.common.v1.Cuboid.Cuboid2D getDefaultInstanceForType() {
        return lunarclient.apollo.common.v1.Cuboid.Cuboid2D.getDefaultInstance();
      }

      @java.lang.Override
      public lunarclient.apollo.common.v1.Cuboid.Cuboid2D build() {
        lunarclient.apollo.common.v1.Cuboid.Cuboid2D result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public lunarclient.apollo.common.v1.Cuboid.Cuboid2D buildPartial() {
        lunarclient.apollo.common.v1.Cuboid.Cuboid2D result = new lunarclient.apollo.common.v1.Cuboid.Cuboid2D(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(lunarclient.apollo.common.v1.Cuboid.Cuboid2D result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.minX_ = minX_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.minZ_ = minZ_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.maxX_ = maxX_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.maxZ_ = maxZ_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof lunarclient.apollo.common.v1.Cuboid.Cuboid2D) {
          return mergeFrom((lunarclient.apollo.common.v1.Cuboid.Cuboid2D)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(lunarclient.apollo.common.v1.Cuboid.Cuboid2D other) {
        if (other == lunarclient.apollo.common.v1.Cuboid.Cuboid2D.getDefaultInstance()) return this;
        if (java.lang.Double.doubleToRawLongBits(other.getMinX()) != 0) {
          setMinX(other.getMinX());
        }
        if (java.lang.Double.doubleToRawLongBits(other.getMinZ()) != 0) {
          setMinZ(other.getMinZ());
        }
        if (java.lang.Double.doubleToRawLongBits(other.getMaxX()) != 0) {
          setMaxX(other.getMaxX());
        }
        if (java.lang.Double.doubleToRawLongBits(other.getMaxZ()) != 0) {
          setMaxZ(other.getMaxZ());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 9: {
                minX_ = input.readDouble();
                bitField0_ |= 0x00000001;
                break;
              } // case 9
              case 17: {
                minZ_ = input.readDouble();
                bitField0_ |= 0x00000002;
                break;
              } // case 17
              case 25: {
                maxX_ = input.readDouble();
                bitField0_ |= 0x00000004;
                break;
              } // case 25
              case 33: {
                maxZ_ = input.readDouble();
                bitField0_ |= 0x00000008;
                break;
              } // case 33
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private double minX_ ;
      /**
       * <code>double min_x = 1 [json_name = "minX"];</code>
       * @return The minX.
       */
      @java.lang.Override
      public double getMinX() {
        return minX_;
      }
      /**
       * <code>double min_x = 1 [json_name = "minX"];</code>
       * @param value The minX to set.
       * @return This builder for chaining.
       */
      public Builder setMinX(double value) {

        minX_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>double min_x = 1 [json_name = "minX"];</code>
       * @return This builder for chaining.
       */
      public Builder clearMinX() {
        bitField0_ = (bitField0_ & ~0x00000001);
        minX_ = 0D;
        onChanged();
        return this;
      }

      private double minZ_ ;
      /**
       * <code>double min_z = 2 [json_name = "minZ"];</code>
       * @return The minZ.
       */
      @java.lang.Override
      public double getMinZ() {
        return minZ_;
      }
      /**
       * <code>double min_z = 2 [json_name = "minZ"];</code>
       * @param value The minZ to set.
       * @return This builder for chaining.
       */
      public Builder setMinZ(double value) {

        minZ_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>double min_z = 2 [json_name = "minZ"];</code>
       * @return This builder for chaining.
       */
      public Builder clearMinZ() {
        bitField0_ = (bitField0_ & ~0x00000002);
        minZ_ = 0D;
        onChanged();
        return this;
      }

      private double maxX_ ;
      /**
       * <code>double max_x = 3 [json_name = "maxX"];</code>
       * @return The maxX.
       */
      @java.lang.Override
      public double getMaxX() {
        return maxX_;
      }
      /**
       * <code>double max_x = 3 [json_name = "maxX"];</code>
       * @param value The maxX to set.
       * @return This builder for chaining.
       */
      public Builder setMaxX(double value) {

        maxX_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>double max_x = 3 [json_name = "maxX"];</code>
       * @return This builder for chaining.
       */
      public Builder clearMaxX() {
        bitField0_ = (bitField0_ & ~0x00000004);
        maxX_ = 0D;
        onChanged();
        return this;
      }

      private double maxZ_ ;
      /**
       * <code>double max_z = 4 [json_name = "maxZ"];</code>
       * @return The maxZ.
       */
      @java.lang.Override
      public double getMaxZ() {
        return maxZ_;
      }
      /**
       * <code>double max_z = 4 [json_name = "maxZ"];</code>
       * @param value The maxZ to set.
       * @return This builder for chaining.
       */
      public Builder setMaxZ(double value) {

        maxZ_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>double max_z = 4 [json_name = "maxZ"];</code>
       * @return This builder for chaining.
       */
      public Builder clearMaxZ() {
        bitField0_ = (bitField0_ & ~0x00000008);
        maxZ_ = 0D;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:lunarclient.apollo.common.v1.Cuboid2D)
    }

    // @@protoc_insertion_point(class_scope:lunarclient.apollo.common.v1.Cuboid2D)
    private static final lunarclient.apollo.common.v1.Cuboid.Cuboid2D DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new lunarclient.apollo.common.v1.Cuboid.Cuboid2D();
    }

    public static lunarclient.apollo.common.v1.Cuboid.Cuboid2D getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Cuboid2D>
        PARSER = new com.google.protobuf.AbstractParser<Cuboid2D>() {
      @java.lang.Override
      public Cuboid2D parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Cuboid2D> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Cuboid2D> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public lunarclient.apollo.common.v1.Cuboid.Cuboid2D getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface Cuboid3DOrBuilder extends
      // @@protoc_insertion_point(interface_extends:lunarclient.apollo.common.v1.Cuboid3D)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>double min_x = 1 [json_name = "minX"];</code>
     * @return The minX.
     */
    double getMinX();

    /**
     * <code>double min_y = 2 [json_name = "minY"];</code>
     * @return The minY.
     */
    double getMinY();

    /**
     * <code>double min_z = 3 [json_name = "minZ"];</code>
     * @return The minZ.
     */
    double getMinZ();

    /**
     * <code>double max_x = 4 [json_name = "maxX"];</code>
     * @return The maxX.
     */
    double getMaxX();

    /**
     * <code>double max_y = 5 [json_name = "maxY"];</code>
     * @return The maxY.
     */
    double getMaxY();

    /**
     * <code>double max_z = 6 [json_name = "maxZ"];</code>
     * @return The maxZ.
     */
    double getMaxZ();
  }
  /**
   * Protobuf type {@code lunarclient.apollo.common.v1.Cuboid3D}
   */
  public static final class Cuboid3D extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:lunarclient.apollo.common.v1.Cuboid3D)
      Cuboid3DOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 1,
        /* suffix= */ "",
        Cuboid3D.class.getName());
    }
    // Use Cuboid3D.newBuilder() to construct.
    private Cuboid3D(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Cuboid3D() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return lunarclient.apollo.common.v1.Cuboid.internal_static_lunarclient_apollo_common_v1_Cuboid3D_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return lunarclient.apollo.common.v1.Cuboid.internal_static_lunarclient_apollo_common_v1_Cuboid3D_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              lunarclient.apollo.common.v1.Cuboid.Cuboid3D.class, lunarclient.apollo.common.v1.Cuboid.Cuboid3D.Builder.class);
    }

    public static final int MIN_X_FIELD_NUMBER = 1;
    private double minX_ = 0D;
    /**
     * <code>double min_x = 1 [json_name = "minX"];</code>
     * @return The minX.
     */
    @java.lang.Override
    public double getMinX() {
      return minX_;
    }

    public static final int MIN_Y_FIELD_NUMBER = 2;
    private double minY_ = 0D;
    /**
     * <code>double min_y = 2 [json_name = "minY"];</code>
     * @return The minY.
     */
    @java.lang.Override
    public double getMinY() {
      return minY_;
    }

    public static final int MIN_Z_FIELD_NUMBER = 3;
    private double minZ_ = 0D;
    /**
     * <code>double min_z = 3 [json_name = "minZ"];</code>
     * @return The minZ.
     */
    @java.lang.Override
    public double getMinZ() {
      return minZ_;
    }

    public static final int MAX_X_FIELD_NUMBER = 4;
    private double maxX_ = 0D;
    /**
     * <code>double max_x = 4 [json_name = "maxX"];</code>
     * @return The maxX.
     */
    @java.lang.Override
    public double getMaxX() {
      return maxX_;
    }

    public static final int MAX_Y_FIELD_NUMBER = 5;
    private double maxY_ = 0D;
    /**
     * <code>double max_y = 5 [json_name = "maxY"];</code>
     * @return The maxY.
     */
    @java.lang.Override
    public double getMaxY() {
      return maxY_;
    }

    public static final int MAX_Z_FIELD_NUMBER = 6;
    private double maxZ_ = 0D;
    /**
     * <code>double max_z = 6 [json_name = "maxZ"];</code>
     * @return The maxZ.
     */
    @java.lang.Override
    public double getMaxZ() {
      return maxZ_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (java.lang.Double.doubleToRawLongBits(minX_) != 0) {
        output.writeDouble(1, minX_);
      }
      if (java.lang.Double.doubleToRawLongBits(minY_) != 0) {
        output.writeDouble(2, minY_);
      }
      if (java.lang.Double.doubleToRawLongBits(minZ_) != 0) {
        output.writeDouble(3, minZ_);
      }
      if (java.lang.Double.doubleToRawLongBits(maxX_) != 0) {
        output.writeDouble(4, maxX_);
      }
      if (java.lang.Double.doubleToRawLongBits(maxY_) != 0) {
        output.writeDouble(5, maxY_);
      }
      if (java.lang.Double.doubleToRawLongBits(maxZ_) != 0) {
        output.writeDouble(6, maxZ_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (java.lang.Double.doubleToRawLongBits(minX_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, minX_);
      }
      if (java.lang.Double.doubleToRawLongBits(minY_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, minY_);
      }
      if (java.lang.Double.doubleToRawLongBits(minZ_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, minZ_);
      }
      if (java.lang.Double.doubleToRawLongBits(maxX_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, maxX_);
      }
      if (java.lang.Double.doubleToRawLongBits(maxY_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, maxY_);
      }
      if (java.lang.Double.doubleToRawLongBits(maxZ_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, maxZ_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof lunarclient.apollo.common.v1.Cuboid.Cuboid3D)) {
        return super.equals(obj);
      }
      lunarclient.apollo.common.v1.Cuboid.Cuboid3D other = (lunarclient.apollo.common.v1.Cuboid.Cuboid3D) obj;

      if (java.lang.Double.doubleToLongBits(getMinX())
          != java.lang.Double.doubleToLongBits(
              other.getMinX())) return false;
      if (java.lang.Double.doubleToLongBits(getMinY())
          != java.lang.Double.doubleToLongBits(
              other.getMinY())) return false;
      if (java.lang.Double.doubleToLongBits(getMinZ())
          != java.lang.Double.doubleToLongBits(
              other.getMinZ())) return false;
      if (java.lang.Double.doubleToLongBits(getMaxX())
          != java.lang.Double.doubleToLongBits(
              other.getMaxX())) return false;
      if (java.lang.Double.doubleToLongBits(getMaxY())
          != java.lang.Double.doubleToLongBits(
              other.getMaxY())) return false;
      if (java.lang.Double.doubleToLongBits(getMaxZ())
          != java.lang.Double.doubleToLongBits(
              other.getMaxZ())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MIN_X_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getMinX()));
      hash = (37 * hash) + MIN_Y_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getMinY()));
      hash = (37 * hash) + MIN_Z_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getMinZ()));
      hash = (37 * hash) + MAX_X_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getMaxX()));
      hash = (37 * hash) + MAX_Y_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getMaxY()));
      hash = (37 * hash) + MAX_Z_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getMaxZ()));
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static lunarclient.apollo.common.v1.Cuboid.Cuboid3D parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lunarclient.apollo.common.v1.Cuboid.Cuboid3D parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lunarclient.apollo.common.v1.Cuboid.Cuboid3D parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lunarclient.apollo.common.v1.Cuboid.Cuboid3D parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lunarclient.apollo.common.v1.Cuboid.Cuboid3D parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lunarclient.apollo.common.v1.Cuboid.Cuboid3D parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lunarclient.apollo.common.v1.Cuboid.Cuboid3D parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static lunarclient.apollo.common.v1.Cuboid.Cuboid3D parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static lunarclient.apollo.common.v1.Cuboid.Cuboid3D parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static lunarclient.apollo.common.v1.Cuboid.Cuboid3D parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static lunarclient.apollo.common.v1.Cuboid.Cuboid3D parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static lunarclient.apollo.common.v1.Cuboid.Cuboid3D parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(lunarclient.apollo.common.v1.Cuboid.Cuboid3D prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code lunarclient.apollo.common.v1.Cuboid3D}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:lunarclient.apollo.common.v1.Cuboid3D)
        lunarclient.apollo.common.v1.Cuboid.Cuboid3DOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return lunarclient.apollo.common.v1.Cuboid.internal_static_lunarclient_apollo_common_v1_Cuboid3D_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return lunarclient.apollo.common.v1.Cuboid.internal_static_lunarclient_apollo_common_v1_Cuboid3D_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                lunarclient.apollo.common.v1.Cuboid.Cuboid3D.class, lunarclient.apollo.common.v1.Cuboid.Cuboid3D.Builder.class);
      }

      // Construct using lunarclient.apollo.common.v1.Cuboid.Cuboid3D.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        minX_ = 0D;
        minY_ = 0D;
        minZ_ = 0D;
        maxX_ = 0D;
        maxY_ = 0D;
        maxZ_ = 0D;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return lunarclient.apollo.common.v1.Cuboid.internal_static_lunarclient_apollo_common_v1_Cuboid3D_descriptor;
      }

      @java.lang.Override
      public lunarclient.apollo.common.v1.Cuboid.Cuboid3D getDefaultInstanceForType() {
        return lunarclient.apollo.common.v1.Cuboid.Cuboid3D.getDefaultInstance();
      }

      @java.lang.Override
      public lunarclient.apollo.common.v1.Cuboid.Cuboid3D build() {
        lunarclient.apollo.common.v1.Cuboid.Cuboid3D result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public lunarclient.apollo.common.v1.Cuboid.Cuboid3D buildPartial() {
        lunarclient.apollo.common.v1.Cuboid.Cuboid3D result = new lunarclient.apollo.common.v1.Cuboid.Cuboid3D(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(lunarclient.apollo.common.v1.Cuboid.Cuboid3D result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.minX_ = minX_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.minY_ = minY_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.minZ_ = minZ_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.maxX_ = maxX_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.maxY_ = maxY_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.maxZ_ = maxZ_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof lunarclient.apollo.common.v1.Cuboid.Cuboid3D) {
          return mergeFrom((lunarclient.apollo.common.v1.Cuboid.Cuboid3D)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(lunarclient.apollo.common.v1.Cuboid.Cuboid3D other) {
        if (other == lunarclient.apollo.common.v1.Cuboid.Cuboid3D.getDefaultInstance()) return this;
        if (java.lang.Double.doubleToRawLongBits(other.getMinX()) != 0) {
          setMinX(other.getMinX());
        }
        if (java.lang.Double.doubleToRawLongBits(other.getMinY()) != 0) {
          setMinY(other.getMinY());
        }
        if (java.lang.Double.doubleToRawLongBits(other.getMinZ()) != 0) {
          setMinZ(other.getMinZ());
        }
        if (java.lang.Double.doubleToRawLongBits(other.getMaxX()) != 0) {
          setMaxX(other.getMaxX());
        }
        if (java.lang.Double.doubleToRawLongBits(other.getMaxY()) != 0) {
          setMaxY(other.getMaxY());
        }
        if (java.lang.Double.doubleToRawLongBits(other.getMaxZ()) != 0) {
          setMaxZ(other.getMaxZ());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 9: {
                minX_ = input.readDouble();
                bitField0_ |= 0x00000001;
                break;
              } // case 9
              case 17: {
                minY_ = input.readDouble();
                bitField0_ |= 0x00000002;
                break;
              } // case 17
              case 25: {
                minZ_ = input.readDouble();
                bitField0_ |= 0x00000004;
                break;
              } // case 25
              case 33: {
                maxX_ = input.readDouble();
                bitField0_ |= 0x00000008;
                break;
              } // case 33
              case 41: {
                maxY_ = input.readDouble();
                bitField0_ |= 0x00000010;
                break;
              } // case 41
              case 49: {
                maxZ_ = input.readDouble();
                bitField0_ |= 0x00000020;
                break;
              } // case 49
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private double minX_ ;
      /**
       * <code>double min_x = 1 [json_name = "minX"];</code>
       * @return The minX.
       */
      @java.lang.Override
      public double getMinX() {
        return minX_;
      }
      /**
       * <code>double min_x = 1 [json_name = "minX"];</code>
       * @param value The minX to set.
       * @return This builder for chaining.
       */
      public Builder setMinX(double value) {

        minX_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>double min_x = 1 [json_name = "minX"];</code>
       * @return This builder for chaining.
       */
      public Builder clearMinX() {
        bitField0_ = (bitField0_ & ~0x00000001);
        minX_ = 0D;
        onChanged();
        return this;
      }

      private double minY_ ;
      /**
       * <code>double min_y = 2 [json_name = "minY"];</code>
       * @return The minY.
       */
      @java.lang.Override
      public double getMinY() {
        return minY_;
      }
      /**
       * <code>double min_y = 2 [json_name = "minY"];</code>
       * @param value The minY to set.
       * @return This builder for chaining.
       */
      public Builder setMinY(double value) {

        minY_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>double min_y = 2 [json_name = "minY"];</code>
       * @return This builder for chaining.
       */
      public Builder clearMinY() {
        bitField0_ = (bitField0_ & ~0x00000002);
        minY_ = 0D;
        onChanged();
        return this;
      }

      private double minZ_ ;
      /**
       * <code>double min_z = 3 [json_name = "minZ"];</code>
       * @return The minZ.
       */
      @java.lang.Override
      public double getMinZ() {
        return minZ_;
      }
      /**
       * <code>double min_z = 3 [json_name = "minZ"];</code>
       * @param value The minZ to set.
       * @return This builder for chaining.
       */
      public Builder setMinZ(double value) {

        minZ_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>double min_z = 3 [json_name = "minZ"];</code>
       * @return This builder for chaining.
       */
      public Builder clearMinZ() {
        bitField0_ = (bitField0_ & ~0x00000004);
        minZ_ = 0D;
        onChanged();
        return this;
      }

      private double maxX_ ;
      /**
       * <code>double max_x = 4 [json_name = "maxX"];</code>
       * @return The maxX.
       */
      @java.lang.Override
      public double getMaxX() {
        return maxX_;
      }
      /**
       * <code>double max_x = 4 [json_name = "maxX"];</code>
       * @param value The maxX to set.
       * @return This builder for chaining.
       */
      public Builder setMaxX(double value) {

        maxX_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>double max_x = 4 [json_name = "maxX"];</code>
       * @return This builder for chaining.
       */
      public Builder clearMaxX() {
        bitField0_ = (bitField0_ & ~0x00000008);
        maxX_ = 0D;
        onChanged();
        return this;
      }

      private double maxY_ ;
      /**
       * <code>double max_y = 5 [json_name = "maxY"];</code>
       * @return The maxY.
       */
      @java.lang.Override
      public double getMaxY() {
        return maxY_;
      }
      /**
       * <code>double max_y = 5 [json_name = "maxY"];</code>
       * @param value The maxY to set.
       * @return This builder for chaining.
       */
      public Builder setMaxY(double value) {

        maxY_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>double max_y = 5 [json_name = "maxY"];</code>
       * @return This builder for chaining.
       */
      public Builder clearMaxY() {
        bitField0_ = (bitField0_ & ~0x00000010);
        maxY_ = 0D;
        onChanged();
        return this;
      }

      private double maxZ_ ;
      /**
       * <code>double max_z = 6 [json_name = "maxZ"];</code>
       * @return The maxZ.
       */
      @java.lang.Override
      public double getMaxZ() {
        return maxZ_;
      }
      /**
       * <code>double max_z = 6 [json_name = "maxZ"];</code>
       * @param value The maxZ to set.
       * @return This builder for chaining.
       */
      public Builder setMaxZ(double value) {

        maxZ_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>double max_z = 6 [json_name = "maxZ"];</code>
       * @return This builder for chaining.
       */
      public Builder clearMaxZ() {
        bitField0_ = (bitField0_ & ~0x00000020);
        maxZ_ = 0D;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:lunarclient.apollo.common.v1.Cuboid3D)
    }

    // @@protoc_insertion_point(class_scope:lunarclient.apollo.common.v1.Cuboid3D)
    private static final lunarclient.apollo.common.v1.Cuboid.Cuboid3D DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new lunarclient.apollo.common.v1.Cuboid.Cuboid3D();
    }

    public static lunarclient.apollo.common.v1.Cuboid.Cuboid3D getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Cuboid3D>
        PARSER = new com.google.protobuf.AbstractParser<Cuboid3D>() {
      @java.lang.Override
      public Cuboid3D parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Cuboid3D> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Cuboid3D> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public lunarclient.apollo.common.v1.Cuboid.Cuboid3D getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lunarclient_apollo_common_v1_Cuboid2D_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lunarclient_apollo_common_v1_Cuboid2D_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lunarclient_apollo_common_v1_Cuboid3D_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lunarclient_apollo_common_v1_Cuboid3D_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n)lunarclient/apollo/common/v1/cuboid.pr" +
      "oto\022\034lunarclient.apollo.common.v1\"^\n\010Cub" +
      "oid2D\022\023\n\005min_x\030\001 \001(\001R\004minX\022\023\n\005min_z\030\002 \001(" +
      "\001R\004minZ\022\023\n\005max_x\030\003 \001(\001R\004maxX\022\023\n\005max_z\030\004 " +
      "\001(\001R\004maxZ\"\210\001\n\010Cuboid3D\022\023\n\005min_x\030\001 \001(\001R\004m" +
      "inX\022\023\n\005min_y\030\002 \001(\001R\004minY\022\023\n\005min_z\030\003 \001(\001R" +
      "\004minZ\022\023\n\005max_x\030\004 \001(\001R\004maxX\022\023\n\005max_y\030\005 \001(" +
      "\001R\004maxY\022\023\n\005max_z\030\006 \001(\001R\004maxZb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_lunarclient_apollo_common_v1_Cuboid2D_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_lunarclient_apollo_common_v1_Cuboid2D_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lunarclient_apollo_common_v1_Cuboid2D_descriptor,
        new java.lang.String[] { "MinX", "MinZ", "MaxX", "MaxZ", });
    internal_static_lunarclient_apollo_common_v1_Cuboid3D_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_lunarclient_apollo_common_v1_Cuboid3D_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lunarclient_apollo_common_v1_Cuboid3D_descriptor,
        new java.lang.String[] { "MinX", "MinY", "MinZ", "MaxX", "MaxY", "MaxZ", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
