// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: lunarclient/apollo/common/v1/entityid.proto
// Protobuf Java Version: 4.31.1

package lunarclient.apollo.common.v1;

@com.google.protobuf.Generated
public final class Entityid {
  private Entityid() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      Entityid.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EntityIdOrBuilder extends
      // @@protoc_insertion_point(interface_extends:lunarclient.apollo.common.v1.EntityId)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 entity_id = 1 [json_name = "entityId"];</code>
     * @return The entityId.
     */
    int getEntityId();

    /**
     * <code>.lunarclient.apollo.common.v1.Uuid entity_uuid = 2 [json_name = "entityUuid"];</code>
     * @return Whether the entityUuid field is set.
     */
    boolean hasEntityUuid();
    /**
     * <code>.lunarclient.apollo.common.v1.Uuid entity_uuid = 2 [json_name = "entityUuid"];</code>
     * @return The entityUuid.
     */
    lunarclient.apollo.common.v1.UuidOuterClass.Uuid getEntityUuid();
    /**
     * <code>.lunarclient.apollo.common.v1.Uuid entity_uuid = 2 [json_name = "entityUuid"];</code>
     */
    lunarclient.apollo.common.v1.UuidOuterClass.UuidOrBuilder getEntityUuidOrBuilder();
  }
  /**
   * Protobuf type {@code lunarclient.apollo.common.v1.EntityId}
   */
  public static final class EntityId extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:lunarclient.apollo.common.v1.EntityId)
      EntityIdOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 1,
        /* suffix= */ "",
        EntityId.class.getName());
    }
    // Use EntityId.newBuilder() to construct.
    private EntityId(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private EntityId() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return lunarclient.apollo.common.v1.Entityid.internal_static_lunarclient_apollo_common_v1_EntityId_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return lunarclient.apollo.common.v1.Entityid.internal_static_lunarclient_apollo_common_v1_EntityId_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              lunarclient.apollo.common.v1.Entityid.EntityId.class, lunarclient.apollo.common.v1.Entityid.EntityId.Builder.class);
    }

    private int bitField0_;
    public static final int ENTITY_ID_FIELD_NUMBER = 1;
    private int entityId_ = 0;
    /**
     * <code>int32 entity_id = 1 [json_name = "entityId"];</code>
     * @return The entityId.
     */
    @java.lang.Override
    public int getEntityId() {
      return entityId_;
    }

    public static final int ENTITY_UUID_FIELD_NUMBER = 2;
    private lunarclient.apollo.common.v1.UuidOuterClass.Uuid entityUuid_;
    /**
     * <code>.lunarclient.apollo.common.v1.Uuid entity_uuid = 2 [json_name = "entityUuid"];</code>
     * @return Whether the entityUuid field is set.
     */
    @java.lang.Override
    public boolean hasEntityUuid() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.lunarclient.apollo.common.v1.Uuid entity_uuid = 2 [json_name = "entityUuid"];</code>
     * @return The entityUuid.
     */
    @java.lang.Override
    public lunarclient.apollo.common.v1.UuidOuterClass.Uuid getEntityUuid() {
      return entityUuid_ == null ? lunarclient.apollo.common.v1.UuidOuterClass.Uuid.getDefaultInstance() : entityUuid_;
    }
    /**
     * <code>.lunarclient.apollo.common.v1.Uuid entity_uuid = 2 [json_name = "entityUuid"];</code>
     */
    @java.lang.Override
    public lunarclient.apollo.common.v1.UuidOuterClass.UuidOrBuilder getEntityUuidOrBuilder() {
      return entityUuid_ == null ? lunarclient.apollo.common.v1.UuidOuterClass.Uuid.getDefaultInstance() : entityUuid_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (entityId_ != 0) {
        output.writeInt32(1, entityId_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(2, getEntityUuid());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (entityId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, entityId_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getEntityUuid());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof lunarclient.apollo.common.v1.Entityid.EntityId)) {
        return super.equals(obj);
      }
      lunarclient.apollo.common.v1.Entityid.EntityId other = (lunarclient.apollo.common.v1.Entityid.EntityId) obj;

      if (getEntityId()
          != other.getEntityId()) return false;
      if (hasEntityUuid() != other.hasEntityUuid()) return false;
      if (hasEntityUuid()) {
        if (!getEntityUuid()
            .equals(other.getEntityUuid())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ENTITY_ID_FIELD_NUMBER;
      hash = (53 * hash) + getEntityId();
      if (hasEntityUuid()) {
        hash = (37 * hash) + ENTITY_UUID_FIELD_NUMBER;
        hash = (53 * hash) + getEntityUuid().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static lunarclient.apollo.common.v1.Entityid.EntityId parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lunarclient.apollo.common.v1.Entityid.EntityId parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lunarclient.apollo.common.v1.Entityid.EntityId parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lunarclient.apollo.common.v1.Entityid.EntityId parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lunarclient.apollo.common.v1.Entityid.EntityId parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lunarclient.apollo.common.v1.Entityid.EntityId parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lunarclient.apollo.common.v1.Entityid.EntityId parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static lunarclient.apollo.common.v1.Entityid.EntityId parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static lunarclient.apollo.common.v1.Entityid.EntityId parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static lunarclient.apollo.common.v1.Entityid.EntityId parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static lunarclient.apollo.common.v1.Entityid.EntityId parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static lunarclient.apollo.common.v1.Entityid.EntityId parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(lunarclient.apollo.common.v1.Entityid.EntityId prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code lunarclient.apollo.common.v1.EntityId}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:lunarclient.apollo.common.v1.EntityId)
        lunarclient.apollo.common.v1.Entityid.EntityIdOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return lunarclient.apollo.common.v1.Entityid.internal_static_lunarclient_apollo_common_v1_EntityId_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return lunarclient.apollo.common.v1.Entityid.internal_static_lunarclient_apollo_common_v1_EntityId_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                lunarclient.apollo.common.v1.Entityid.EntityId.class, lunarclient.apollo.common.v1.Entityid.EntityId.Builder.class);
      }

      // Construct using lunarclient.apollo.common.v1.Entityid.EntityId.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          internalGetEntityUuidFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        entityId_ = 0;
        entityUuid_ = null;
        if (entityUuidBuilder_ != null) {
          entityUuidBuilder_.dispose();
          entityUuidBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return lunarclient.apollo.common.v1.Entityid.internal_static_lunarclient_apollo_common_v1_EntityId_descriptor;
      }

      @java.lang.Override
      public lunarclient.apollo.common.v1.Entityid.EntityId getDefaultInstanceForType() {
        return lunarclient.apollo.common.v1.Entityid.EntityId.getDefaultInstance();
      }

      @java.lang.Override
      public lunarclient.apollo.common.v1.Entityid.EntityId build() {
        lunarclient.apollo.common.v1.Entityid.EntityId result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public lunarclient.apollo.common.v1.Entityid.EntityId buildPartial() {
        lunarclient.apollo.common.v1.Entityid.EntityId result = new lunarclient.apollo.common.v1.Entityid.EntityId(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(lunarclient.apollo.common.v1.Entityid.EntityId result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.entityId_ = entityId_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.entityUuid_ = entityUuidBuilder_ == null
              ? entityUuid_
              : entityUuidBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof lunarclient.apollo.common.v1.Entityid.EntityId) {
          return mergeFrom((lunarclient.apollo.common.v1.Entityid.EntityId)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(lunarclient.apollo.common.v1.Entityid.EntityId other) {
        if (other == lunarclient.apollo.common.v1.Entityid.EntityId.getDefaultInstance()) return this;
        if (other.getEntityId() != 0) {
          setEntityId(other.getEntityId());
        }
        if (other.hasEntityUuid()) {
          mergeEntityUuid(other.getEntityUuid());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                entityId_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                input.readMessage(
                    internalGetEntityUuidFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int entityId_ ;
      /**
       * <code>int32 entity_id = 1 [json_name = "entityId"];</code>
       * @return The entityId.
       */
      @java.lang.Override
      public int getEntityId() {
        return entityId_;
      }
      /**
       * <code>int32 entity_id = 1 [json_name = "entityId"];</code>
       * @param value The entityId to set.
       * @return This builder for chaining.
       */
      public Builder setEntityId(int value) {

        entityId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 entity_id = 1 [json_name = "entityId"];</code>
       * @return This builder for chaining.
       */
      public Builder clearEntityId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        entityId_ = 0;
        onChanged();
        return this;
      }

      private lunarclient.apollo.common.v1.UuidOuterClass.Uuid entityUuid_;
      private com.google.protobuf.SingleFieldBuilder<
          lunarclient.apollo.common.v1.UuidOuterClass.Uuid, lunarclient.apollo.common.v1.UuidOuterClass.Uuid.Builder, lunarclient.apollo.common.v1.UuidOuterClass.UuidOrBuilder> entityUuidBuilder_;
      /**
       * <code>.lunarclient.apollo.common.v1.Uuid entity_uuid = 2 [json_name = "entityUuid"];</code>
       * @return Whether the entityUuid field is set.
       */
      public boolean hasEntityUuid() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>.lunarclient.apollo.common.v1.Uuid entity_uuid = 2 [json_name = "entityUuid"];</code>
       * @return The entityUuid.
       */
      public lunarclient.apollo.common.v1.UuidOuterClass.Uuid getEntityUuid() {
        if (entityUuidBuilder_ == null) {
          return entityUuid_ == null ? lunarclient.apollo.common.v1.UuidOuterClass.Uuid.getDefaultInstance() : entityUuid_;
        } else {
          return entityUuidBuilder_.getMessage();
        }
      }
      /**
       * <code>.lunarclient.apollo.common.v1.Uuid entity_uuid = 2 [json_name = "entityUuid"];</code>
       */
      public Builder setEntityUuid(lunarclient.apollo.common.v1.UuidOuterClass.Uuid value) {
        if (entityUuidBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          entityUuid_ = value;
        } else {
          entityUuidBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.lunarclient.apollo.common.v1.Uuid entity_uuid = 2 [json_name = "entityUuid"];</code>
       */
      public Builder setEntityUuid(
          lunarclient.apollo.common.v1.UuidOuterClass.Uuid.Builder builderForValue) {
        if (entityUuidBuilder_ == null) {
          entityUuid_ = builderForValue.build();
        } else {
          entityUuidBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.lunarclient.apollo.common.v1.Uuid entity_uuid = 2 [json_name = "entityUuid"];</code>
       */
      public Builder mergeEntityUuid(lunarclient.apollo.common.v1.UuidOuterClass.Uuid value) {
        if (entityUuidBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            entityUuid_ != null &&
            entityUuid_ != lunarclient.apollo.common.v1.UuidOuterClass.Uuid.getDefaultInstance()) {
            getEntityUuidBuilder().mergeFrom(value);
          } else {
            entityUuid_ = value;
          }
        } else {
          entityUuidBuilder_.mergeFrom(value);
        }
        if (entityUuid_ != null) {
          bitField0_ |= 0x00000002;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.lunarclient.apollo.common.v1.Uuid entity_uuid = 2 [json_name = "entityUuid"];</code>
       */
      public Builder clearEntityUuid() {
        bitField0_ = (bitField0_ & ~0x00000002);
        entityUuid_ = null;
        if (entityUuidBuilder_ != null) {
          entityUuidBuilder_.dispose();
          entityUuidBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.lunarclient.apollo.common.v1.Uuid entity_uuid = 2 [json_name = "entityUuid"];</code>
       */
      public lunarclient.apollo.common.v1.UuidOuterClass.Uuid.Builder getEntityUuidBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return internalGetEntityUuidFieldBuilder().getBuilder();
      }
      /**
       * <code>.lunarclient.apollo.common.v1.Uuid entity_uuid = 2 [json_name = "entityUuid"];</code>
       */
      public lunarclient.apollo.common.v1.UuidOuterClass.UuidOrBuilder getEntityUuidOrBuilder() {
        if (entityUuidBuilder_ != null) {
          return entityUuidBuilder_.getMessageOrBuilder();
        } else {
          return entityUuid_ == null ?
              lunarclient.apollo.common.v1.UuidOuterClass.Uuid.getDefaultInstance() : entityUuid_;
        }
      }
      /**
       * <code>.lunarclient.apollo.common.v1.Uuid entity_uuid = 2 [json_name = "entityUuid"];</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          lunarclient.apollo.common.v1.UuidOuterClass.Uuid, lunarclient.apollo.common.v1.UuidOuterClass.Uuid.Builder, lunarclient.apollo.common.v1.UuidOuterClass.UuidOrBuilder> 
          internalGetEntityUuidFieldBuilder() {
        if (entityUuidBuilder_ == null) {
          entityUuidBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              lunarclient.apollo.common.v1.UuidOuterClass.Uuid, lunarclient.apollo.common.v1.UuidOuterClass.Uuid.Builder, lunarclient.apollo.common.v1.UuidOuterClass.UuidOrBuilder>(
                  getEntityUuid(),
                  getParentForChildren(),
                  isClean());
          entityUuid_ = null;
        }
        return entityUuidBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:lunarclient.apollo.common.v1.EntityId)
    }

    // @@protoc_insertion_point(class_scope:lunarclient.apollo.common.v1.EntityId)
    private static final lunarclient.apollo.common.v1.Entityid.EntityId DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new lunarclient.apollo.common.v1.Entityid.EntityId();
    }

    public static lunarclient.apollo.common.v1.Entityid.EntityId getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EntityId>
        PARSER = new com.google.protobuf.AbstractParser<EntityId>() {
      @java.lang.Override
      public EntityId parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<EntityId> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EntityId> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public lunarclient.apollo.common.v1.Entityid.EntityId getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lunarclient_apollo_common_v1_EntityId_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lunarclient_apollo_common_v1_EntityId_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n+lunarclient/apollo/common/v1/entityid." +
      "proto\022\034lunarclient.apollo.common.v1\032\'lun" +
      "arclient/apollo/common/v1/uuid.proto\"l\n\010" +
      "EntityId\022\033\n\tentity_id\030\001 \001(\005R\010entityId\022C\n" +
      "\013entity_uuid\030\002 \001(\0132\".lunarclient.apollo." +
      "common.v1.UuidR\nentityUuidb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          lunarclient.apollo.common.v1.UuidOuterClass.getDescriptor(),
        });
    internal_static_lunarclient_apollo_common_v1_EntityId_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_lunarclient_apollo_common_v1_EntityId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lunarclient_apollo_common_v1_EntityId_descriptor,
        new java.lang.String[] { "EntityId", "EntityUuid", });
    descriptor.resolveAllFeaturesImmutable();
    lunarclient.apollo.common.v1.UuidOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
