// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: lunarclient/apollo/common/v1/location.proto
// Protobuf Java Version: 4.31.1

package lunarclient.apollo.common.v1;

@com.google.protobuf.Generated
public final class LocationOuterClass {
  private LocationOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      LocationOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BlockLocationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:lunarclient.apollo.common.v1.BlockLocation)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string world = 1 [json_name = "world"];</code>
     * @return The world.
     */
    java.lang.String getWorld();
    /**
     * <code>string world = 1 [json_name = "world"];</code>
     * @return The bytes for world.
     */
    com.google.protobuf.ByteString
        getWorldBytes();

    /**
     * <code>sint32 x = 2 [json_name = "x"];</code>
     * @return The x.
     */
    int getX();

    /**
     * <code>sint32 y = 3 [json_name = "y"];</code>
     * @return The y.
     */
    int getY();

    /**
     * <code>sint32 z = 4 [json_name = "z"];</code>
     * @return The z.
     */
    int getZ();
  }
  /**
   * Protobuf type {@code lunarclient.apollo.common.v1.BlockLocation}
   */
  public static final class BlockLocation extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:lunarclient.apollo.common.v1.BlockLocation)
      BlockLocationOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 1,
        /* suffix= */ "",
        BlockLocation.class.getName());
    }
    // Use BlockLocation.newBuilder() to construct.
    private BlockLocation(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private BlockLocation() {
      world_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return lunarclient.apollo.common.v1.LocationOuterClass.internal_static_lunarclient_apollo_common_v1_BlockLocation_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return lunarclient.apollo.common.v1.LocationOuterClass.internal_static_lunarclient_apollo_common_v1_BlockLocation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              lunarclient.apollo.common.v1.LocationOuterClass.BlockLocation.class, lunarclient.apollo.common.v1.LocationOuterClass.BlockLocation.Builder.class);
    }

    public static final int WORLD_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object world_ = "";
    /**
     * <code>string world = 1 [json_name = "world"];</code>
     * @return The world.
     */
    @java.lang.Override
    public java.lang.String getWorld() {
      java.lang.Object ref = world_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        world_ = s;
        return s;
      }
    }
    /**
     * <code>string world = 1 [json_name = "world"];</code>
     * @return The bytes for world.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getWorldBytes() {
      java.lang.Object ref = world_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        world_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int X_FIELD_NUMBER = 2;
    private int x_ = 0;
    /**
     * <code>sint32 x = 2 [json_name = "x"];</code>
     * @return The x.
     */
    @java.lang.Override
    public int getX() {
      return x_;
    }

    public static final int Y_FIELD_NUMBER = 3;
    private int y_ = 0;
    /**
     * <code>sint32 y = 3 [json_name = "y"];</code>
     * @return The y.
     */
    @java.lang.Override
    public int getY() {
      return y_;
    }

    public static final int Z_FIELD_NUMBER = 4;
    private int z_ = 0;
    /**
     * <code>sint32 z = 4 [json_name = "z"];</code>
     * @return The z.
     */
    @java.lang.Override
    public int getZ() {
      return z_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(world_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, world_);
      }
      if (x_ != 0) {
        output.writeSInt32(2, x_);
      }
      if (y_ != 0) {
        output.writeSInt32(3, y_);
      }
      if (z_ != 0) {
        output.writeSInt32(4, z_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(world_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, world_);
      }
      if (x_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(2, x_);
      }
      if (y_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(3, y_);
      }
      if (z_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(4, z_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof lunarclient.apollo.common.v1.LocationOuterClass.BlockLocation)) {
        return super.equals(obj);
      }
      lunarclient.apollo.common.v1.LocationOuterClass.BlockLocation other = (lunarclient.apollo.common.v1.LocationOuterClass.BlockLocation) obj;

      if (!getWorld()
          .equals(other.getWorld())) return false;
      if (getX()
          != other.getX()) return false;
      if (getY()
          != other.getY()) return false;
      if (getZ()
          != other.getZ()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + WORLD_FIELD_NUMBER;
      hash = (53 * hash) + getWorld().hashCode();
      hash = (37 * hash) + X_FIELD_NUMBER;
      hash = (53 * hash) + getX();
      hash = (37 * hash) + Y_FIELD_NUMBER;
      hash = (53 * hash) + getY();
      hash = (37 * hash) + Z_FIELD_NUMBER;
      hash = (53 * hash) + getZ();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static lunarclient.apollo.common.v1.LocationOuterClass.BlockLocation parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lunarclient.apollo.common.v1.LocationOuterClass.BlockLocation parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lunarclient.apollo.common.v1.LocationOuterClass.BlockLocation parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lunarclient.apollo.common.v1.LocationOuterClass.BlockLocation parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lunarclient.apollo.common.v1.LocationOuterClass.BlockLocation parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lunarclient.apollo.common.v1.LocationOuterClass.BlockLocation parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lunarclient.apollo.common.v1.LocationOuterClass.BlockLocation parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static lunarclient.apollo.common.v1.LocationOuterClass.BlockLocation parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static lunarclient.apollo.common.v1.LocationOuterClass.BlockLocation parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static lunarclient.apollo.common.v1.LocationOuterClass.BlockLocation parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static lunarclient.apollo.common.v1.LocationOuterClass.BlockLocation parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static lunarclient.apollo.common.v1.LocationOuterClass.BlockLocation parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(lunarclient.apollo.common.v1.LocationOuterClass.BlockLocation prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code lunarclient.apollo.common.v1.BlockLocation}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:lunarclient.apollo.common.v1.BlockLocation)
        lunarclient.apollo.common.v1.LocationOuterClass.BlockLocationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return lunarclient.apollo.common.v1.LocationOuterClass.internal_static_lunarclient_apollo_common_v1_BlockLocation_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return lunarclient.apollo.common.v1.LocationOuterClass.internal_static_lunarclient_apollo_common_v1_BlockLocation_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                lunarclient.apollo.common.v1.LocationOuterClass.BlockLocation.class, lunarclient.apollo.common.v1.LocationOuterClass.BlockLocation.Builder.class);
      }

      // Construct using lunarclient.apollo.common.v1.LocationOuterClass.BlockLocation.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        world_ = "";
        x_ = 0;
        y_ = 0;
        z_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return lunarclient.apollo.common.v1.LocationOuterClass.internal_static_lunarclient_apollo_common_v1_BlockLocation_descriptor;
      }

      @java.lang.Override
      public lunarclient.apollo.common.v1.LocationOuterClass.BlockLocation getDefaultInstanceForType() {
        return lunarclient.apollo.common.v1.LocationOuterClass.BlockLocation.getDefaultInstance();
      }

      @java.lang.Override
      public lunarclient.apollo.common.v1.LocationOuterClass.BlockLocation build() {
        lunarclient.apollo.common.v1.LocationOuterClass.BlockLocation result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public lunarclient.apollo.common.v1.LocationOuterClass.BlockLocation buildPartial() {
        lunarclient.apollo.common.v1.LocationOuterClass.BlockLocation result = new lunarclient.apollo.common.v1.LocationOuterClass.BlockLocation(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(lunarclient.apollo.common.v1.LocationOuterClass.BlockLocation result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.world_ = world_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.x_ = x_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.y_ = y_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.z_ = z_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof lunarclient.apollo.common.v1.LocationOuterClass.BlockLocation) {
          return mergeFrom((lunarclient.apollo.common.v1.LocationOuterClass.BlockLocation)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(lunarclient.apollo.common.v1.LocationOuterClass.BlockLocation other) {
        if (other == lunarclient.apollo.common.v1.LocationOuterClass.BlockLocation.getDefaultInstance()) return this;
        if (!other.getWorld().isEmpty()) {
          world_ = other.world_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.getX() != 0) {
          setX(other.getX());
        }
        if (other.getY() != 0) {
          setY(other.getY());
        }
        if (other.getZ() != 0) {
          setZ(other.getZ());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                world_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                x_ = input.readSInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                y_ = input.readSInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                z_ = input.readSInt32();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object world_ = "";
      /**
       * <code>string world = 1 [json_name = "world"];</code>
       * @return The world.
       */
      public java.lang.String getWorld() {
        java.lang.Object ref = world_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          world_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string world = 1 [json_name = "world"];</code>
       * @return The bytes for world.
       */
      public com.google.protobuf.ByteString
          getWorldBytes() {
        java.lang.Object ref = world_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          world_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string world = 1 [json_name = "world"];</code>
       * @param value The world to set.
       * @return This builder for chaining.
       */
      public Builder setWorld(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        world_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string world = 1 [json_name = "world"];</code>
       * @return This builder for chaining.
       */
      public Builder clearWorld() {
        world_ = getDefaultInstance().getWorld();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string world = 1 [json_name = "world"];</code>
       * @param value The bytes for world to set.
       * @return This builder for chaining.
       */
      public Builder setWorldBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        world_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private int x_ ;
      /**
       * <code>sint32 x = 2 [json_name = "x"];</code>
       * @return The x.
       */
      @java.lang.Override
      public int getX() {
        return x_;
      }
      /**
       * <code>sint32 x = 2 [json_name = "x"];</code>
       * @param value The x to set.
       * @return This builder for chaining.
       */
      public Builder setX(int value) {

        x_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>sint32 x = 2 [json_name = "x"];</code>
       * @return This builder for chaining.
       */
      public Builder clearX() {
        bitField0_ = (bitField0_ & ~0x00000002);
        x_ = 0;
        onChanged();
        return this;
      }

      private int y_ ;
      /**
       * <code>sint32 y = 3 [json_name = "y"];</code>
       * @return The y.
       */
      @java.lang.Override
      public int getY() {
        return y_;
      }
      /**
       * <code>sint32 y = 3 [json_name = "y"];</code>
       * @param value The y to set.
       * @return This builder for chaining.
       */
      public Builder setY(int value) {

        y_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>sint32 y = 3 [json_name = "y"];</code>
       * @return This builder for chaining.
       */
      public Builder clearY() {
        bitField0_ = (bitField0_ & ~0x00000004);
        y_ = 0;
        onChanged();
        return this;
      }

      private int z_ ;
      /**
       * <code>sint32 z = 4 [json_name = "z"];</code>
       * @return The z.
       */
      @java.lang.Override
      public int getZ() {
        return z_;
      }
      /**
       * <code>sint32 z = 4 [json_name = "z"];</code>
       * @param value The z to set.
       * @return This builder for chaining.
       */
      public Builder setZ(int value) {

        z_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>sint32 z = 4 [json_name = "z"];</code>
       * @return This builder for chaining.
       */
      public Builder clearZ() {
        bitField0_ = (bitField0_ & ~0x00000008);
        z_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:lunarclient.apollo.common.v1.BlockLocation)
    }

    // @@protoc_insertion_point(class_scope:lunarclient.apollo.common.v1.BlockLocation)
    private static final lunarclient.apollo.common.v1.LocationOuterClass.BlockLocation DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new lunarclient.apollo.common.v1.LocationOuterClass.BlockLocation();
    }

    public static lunarclient.apollo.common.v1.LocationOuterClass.BlockLocation getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BlockLocation>
        PARSER = new com.google.protobuf.AbstractParser<BlockLocation>() {
      @java.lang.Override
      public BlockLocation parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<BlockLocation> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BlockLocation> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public lunarclient.apollo.common.v1.LocationOuterClass.BlockLocation getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PlayerLocationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:lunarclient.apollo.common.v1.PlayerLocation)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.lunarclient.apollo.common.v1.Location location = 1 [json_name = "location"];</code>
     * @return Whether the location field is set.
     */
    boolean hasLocation();
    /**
     * <code>.lunarclient.apollo.common.v1.Location location = 1 [json_name = "location"];</code>
     * @return The location.
     */
    lunarclient.apollo.common.v1.LocationOuterClass.Location getLocation();
    /**
     * <code>.lunarclient.apollo.common.v1.Location location = 1 [json_name = "location"];</code>
     */
    lunarclient.apollo.common.v1.LocationOuterClass.LocationOrBuilder getLocationOrBuilder();

    /**
     * <code>float yaw = 2 [json_name = "yaw"];</code>
     * @return The yaw.
     */
    float getYaw();

    /**
     * <code>float pitch = 3 [json_name = "pitch"];</code>
     * @return The pitch.
     */
    float getPitch();
  }
  /**
   * Protobuf type {@code lunarclient.apollo.common.v1.PlayerLocation}
   */
  public static final class PlayerLocation extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:lunarclient.apollo.common.v1.PlayerLocation)
      PlayerLocationOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 1,
        /* suffix= */ "",
        PlayerLocation.class.getName());
    }
    // Use PlayerLocation.newBuilder() to construct.
    private PlayerLocation(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private PlayerLocation() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return lunarclient.apollo.common.v1.LocationOuterClass.internal_static_lunarclient_apollo_common_v1_PlayerLocation_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return lunarclient.apollo.common.v1.LocationOuterClass.internal_static_lunarclient_apollo_common_v1_PlayerLocation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              lunarclient.apollo.common.v1.LocationOuterClass.PlayerLocation.class, lunarclient.apollo.common.v1.LocationOuterClass.PlayerLocation.Builder.class);
    }

    private int bitField0_;
    public static final int LOCATION_FIELD_NUMBER = 1;
    private lunarclient.apollo.common.v1.LocationOuterClass.Location location_;
    /**
     * <code>.lunarclient.apollo.common.v1.Location location = 1 [json_name = "location"];</code>
     * @return Whether the location field is set.
     */
    @java.lang.Override
    public boolean hasLocation() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.lunarclient.apollo.common.v1.Location location = 1 [json_name = "location"];</code>
     * @return The location.
     */
    @java.lang.Override
    public lunarclient.apollo.common.v1.LocationOuterClass.Location getLocation() {
      return location_ == null ? lunarclient.apollo.common.v1.LocationOuterClass.Location.getDefaultInstance() : location_;
    }
    /**
     * <code>.lunarclient.apollo.common.v1.Location location = 1 [json_name = "location"];</code>
     */
    @java.lang.Override
    public lunarclient.apollo.common.v1.LocationOuterClass.LocationOrBuilder getLocationOrBuilder() {
      return location_ == null ? lunarclient.apollo.common.v1.LocationOuterClass.Location.getDefaultInstance() : location_;
    }

    public static final int YAW_FIELD_NUMBER = 2;
    private float yaw_ = 0F;
    /**
     * <code>float yaw = 2 [json_name = "yaw"];</code>
     * @return The yaw.
     */
    @java.lang.Override
    public float getYaw() {
      return yaw_;
    }

    public static final int PITCH_FIELD_NUMBER = 3;
    private float pitch_ = 0F;
    /**
     * <code>float pitch = 3 [json_name = "pitch"];</code>
     * @return The pitch.
     */
    @java.lang.Override
    public float getPitch() {
      return pitch_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getLocation());
      }
      if (java.lang.Float.floatToRawIntBits(yaw_) != 0) {
        output.writeFloat(2, yaw_);
      }
      if (java.lang.Float.floatToRawIntBits(pitch_) != 0) {
        output.writeFloat(3, pitch_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getLocation());
      }
      if (java.lang.Float.floatToRawIntBits(yaw_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, yaw_);
      }
      if (java.lang.Float.floatToRawIntBits(pitch_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, pitch_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof lunarclient.apollo.common.v1.LocationOuterClass.PlayerLocation)) {
        return super.equals(obj);
      }
      lunarclient.apollo.common.v1.LocationOuterClass.PlayerLocation other = (lunarclient.apollo.common.v1.LocationOuterClass.PlayerLocation) obj;

      if (hasLocation() != other.hasLocation()) return false;
      if (hasLocation()) {
        if (!getLocation()
            .equals(other.getLocation())) return false;
      }
      if (java.lang.Float.floatToIntBits(getYaw())
          != java.lang.Float.floatToIntBits(
              other.getYaw())) return false;
      if (java.lang.Float.floatToIntBits(getPitch())
          != java.lang.Float.floatToIntBits(
              other.getPitch())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasLocation()) {
        hash = (37 * hash) + LOCATION_FIELD_NUMBER;
        hash = (53 * hash) + getLocation().hashCode();
      }
      hash = (37 * hash) + YAW_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getYaw());
      hash = (37 * hash) + PITCH_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getPitch());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static lunarclient.apollo.common.v1.LocationOuterClass.PlayerLocation parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lunarclient.apollo.common.v1.LocationOuterClass.PlayerLocation parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lunarclient.apollo.common.v1.LocationOuterClass.PlayerLocation parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lunarclient.apollo.common.v1.LocationOuterClass.PlayerLocation parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lunarclient.apollo.common.v1.LocationOuterClass.PlayerLocation parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lunarclient.apollo.common.v1.LocationOuterClass.PlayerLocation parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lunarclient.apollo.common.v1.LocationOuterClass.PlayerLocation parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static lunarclient.apollo.common.v1.LocationOuterClass.PlayerLocation parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static lunarclient.apollo.common.v1.LocationOuterClass.PlayerLocation parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static lunarclient.apollo.common.v1.LocationOuterClass.PlayerLocation parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static lunarclient.apollo.common.v1.LocationOuterClass.PlayerLocation parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static lunarclient.apollo.common.v1.LocationOuterClass.PlayerLocation parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(lunarclient.apollo.common.v1.LocationOuterClass.PlayerLocation prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code lunarclient.apollo.common.v1.PlayerLocation}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:lunarclient.apollo.common.v1.PlayerLocation)
        lunarclient.apollo.common.v1.LocationOuterClass.PlayerLocationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return lunarclient.apollo.common.v1.LocationOuterClass.internal_static_lunarclient_apollo_common_v1_PlayerLocation_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return lunarclient.apollo.common.v1.LocationOuterClass.internal_static_lunarclient_apollo_common_v1_PlayerLocation_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                lunarclient.apollo.common.v1.LocationOuterClass.PlayerLocation.class, lunarclient.apollo.common.v1.LocationOuterClass.PlayerLocation.Builder.class);
      }

      // Construct using lunarclient.apollo.common.v1.LocationOuterClass.PlayerLocation.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          internalGetLocationFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        location_ = null;
        if (locationBuilder_ != null) {
          locationBuilder_.dispose();
          locationBuilder_ = null;
        }
        yaw_ = 0F;
        pitch_ = 0F;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return lunarclient.apollo.common.v1.LocationOuterClass.internal_static_lunarclient_apollo_common_v1_PlayerLocation_descriptor;
      }

      @java.lang.Override
      public lunarclient.apollo.common.v1.LocationOuterClass.PlayerLocation getDefaultInstanceForType() {
        return lunarclient.apollo.common.v1.LocationOuterClass.PlayerLocation.getDefaultInstance();
      }

      @java.lang.Override
      public lunarclient.apollo.common.v1.LocationOuterClass.PlayerLocation build() {
        lunarclient.apollo.common.v1.LocationOuterClass.PlayerLocation result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public lunarclient.apollo.common.v1.LocationOuterClass.PlayerLocation buildPartial() {
        lunarclient.apollo.common.v1.LocationOuterClass.PlayerLocation result = new lunarclient.apollo.common.v1.LocationOuterClass.PlayerLocation(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(lunarclient.apollo.common.v1.LocationOuterClass.PlayerLocation result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.location_ = locationBuilder_ == null
              ? location_
              : locationBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.yaw_ = yaw_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.pitch_ = pitch_;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof lunarclient.apollo.common.v1.LocationOuterClass.PlayerLocation) {
          return mergeFrom((lunarclient.apollo.common.v1.LocationOuterClass.PlayerLocation)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(lunarclient.apollo.common.v1.LocationOuterClass.PlayerLocation other) {
        if (other == lunarclient.apollo.common.v1.LocationOuterClass.PlayerLocation.getDefaultInstance()) return this;
        if (other.hasLocation()) {
          mergeLocation(other.getLocation());
        }
        if (java.lang.Float.floatToRawIntBits(other.getYaw()) != 0) {
          setYaw(other.getYaw());
        }
        if (java.lang.Float.floatToRawIntBits(other.getPitch()) != 0) {
          setPitch(other.getPitch());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    internalGetLocationFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 21: {
                yaw_ = input.readFloat();
                bitField0_ |= 0x00000002;
                break;
              } // case 21
              case 29: {
                pitch_ = input.readFloat();
                bitField0_ |= 0x00000004;
                break;
              } // case 29
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private lunarclient.apollo.common.v1.LocationOuterClass.Location location_;
      private com.google.protobuf.SingleFieldBuilder<
          lunarclient.apollo.common.v1.LocationOuterClass.Location, lunarclient.apollo.common.v1.LocationOuterClass.Location.Builder, lunarclient.apollo.common.v1.LocationOuterClass.LocationOrBuilder> locationBuilder_;
      /**
       * <code>.lunarclient.apollo.common.v1.Location location = 1 [json_name = "location"];</code>
       * @return Whether the location field is set.
       */
      public boolean hasLocation() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.lunarclient.apollo.common.v1.Location location = 1 [json_name = "location"];</code>
       * @return The location.
       */
      public lunarclient.apollo.common.v1.LocationOuterClass.Location getLocation() {
        if (locationBuilder_ == null) {
          return location_ == null ? lunarclient.apollo.common.v1.LocationOuterClass.Location.getDefaultInstance() : location_;
        } else {
          return locationBuilder_.getMessage();
        }
      }
      /**
       * <code>.lunarclient.apollo.common.v1.Location location = 1 [json_name = "location"];</code>
       */
      public Builder setLocation(lunarclient.apollo.common.v1.LocationOuterClass.Location value) {
        if (locationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          location_ = value;
        } else {
          locationBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.lunarclient.apollo.common.v1.Location location = 1 [json_name = "location"];</code>
       */
      public Builder setLocation(
          lunarclient.apollo.common.v1.LocationOuterClass.Location.Builder builderForValue) {
        if (locationBuilder_ == null) {
          location_ = builderForValue.build();
        } else {
          locationBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.lunarclient.apollo.common.v1.Location location = 1 [json_name = "location"];</code>
       */
      public Builder mergeLocation(lunarclient.apollo.common.v1.LocationOuterClass.Location value) {
        if (locationBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            location_ != null &&
            location_ != lunarclient.apollo.common.v1.LocationOuterClass.Location.getDefaultInstance()) {
            getLocationBuilder().mergeFrom(value);
          } else {
            location_ = value;
          }
        } else {
          locationBuilder_.mergeFrom(value);
        }
        if (location_ != null) {
          bitField0_ |= 0x00000001;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.lunarclient.apollo.common.v1.Location location = 1 [json_name = "location"];</code>
       */
      public Builder clearLocation() {
        bitField0_ = (bitField0_ & ~0x00000001);
        location_ = null;
        if (locationBuilder_ != null) {
          locationBuilder_.dispose();
          locationBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.lunarclient.apollo.common.v1.Location location = 1 [json_name = "location"];</code>
       */
      public lunarclient.apollo.common.v1.LocationOuterClass.Location.Builder getLocationBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return internalGetLocationFieldBuilder().getBuilder();
      }
      /**
       * <code>.lunarclient.apollo.common.v1.Location location = 1 [json_name = "location"];</code>
       */
      public lunarclient.apollo.common.v1.LocationOuterClass.LocationOrBuilder getLocationOrBuilder() {
        if (locationBuilder_ != null) {
          return locationBuilder_.getMessageOrBuilder();
        } else {
          return location_ == null ?
              lunarclient.apollo.common.v1.LocationOuterClass.Location.getDefaultInstance() : location_;
        }
      }
      /**
       * <code>.lunarclient.apollo.common.v1.Location location = 1 [json_name = "location"];</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          lunarclient.apollo.common.v1.LocationOuterClass.Location, lunarclient.apollo.common.v1.LocationOuterClass.Location.Builder, lunarclient.apollo.common.v1.LocationOuterClass.LocationOrBuilder> 
          internalGetLocationFieldBuilder() {
        if (locationBuilder_ == null) {
          locationBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              lunarclient.apollo.common.v1.LocationOuterClass.Location, lunarclient.apollo.common.v1.LocationOuterClass.Location.Builder, lunarclient.apollo.common.v1.LocationOuterClass.LocationOrBuilder>(
                  getLocation(),
                  getParentForChildren(),
                  isClean());
          location_ = null;
        }
        return locationBuilder_;
      }

      private float yaw_ ;
      /**
       * <code>float yaw = 2 [json_name = "yaw"];</code>
       * @return The yaw.
       */
      @java.lang.Override
      public float getYaw() {
        return yaw_;
      }
      /**
       * <code>float yaw = 2 [json_name = "yaw"];</code>
       * @param value The yaw to set.
       * @return This builder for chaining.
       */
      public Builder setYaw(float value) {

        yaw_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>float yaw = 2 [json_name = "yaw"];</code>
       * @return This builder for chaining.
       */
      public Builder clearYaw() {
        bitField0_ = (bitField0_ & ~0x00000002);
        yaw_ = 0F;
        onChanged();
        return this;
      }

      private float pitch_ ;
      /**
       * <code>float pitch = 3 [json_name = "pitch"];</code>
       * @return The pitch.
       */
      @java.lang.Override
      public float getPitch() {
        return pitch_;
      }
      /**
       * <code>float pitch = 3 [json_name = "pitch"];</code>
       * @param value The pitch to set.
       * @return This builder for chaining.
       */
      public Builder setPitch(float value) {

        pitch_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>float pitch = 3 [json_name = "pitch"];</code>
       * @return This builder for chaining.
       */
      public Builder clearPitch() {
        bitField0_ = (bitField0_ & ~0x00000004);
        pitch_ = 0F;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:lunarclient.apollo.common.v1.PlayerLocation)
    }

    // @@protoc_insertion_point(class_scope:lunarclient.apollo.common.v1.PlayerLocation)
    private static final lunarclient.apollo.common.v1.LocationOuterClass.PlayerLocation DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new lunarclient.apollo.common.v1.LocationOuterClass.PlayerLocation();
    }

    public static lunarclient.apollo.common.v1.LocationOuterClass.PlayerLocation getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PlayerLocation>
        PARSER = new com.google.protobuf.AbstractParser<PlayerLocation>() {
      @java.lang.Override
      public PlayerLocation parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PlayerLocation> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PlayerLocation> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public lunarclient.apollo.common.v1.LocationOuterClass.PlayerLocation getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface LocationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:lunarclient.apollo.common.v1.Location)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string world = 1 [json_name = "world"];</code>
     * @return The world.
     */
    java.lang.String getWorld();
    /**
     * <code>string world = 1 [json_name = "world"];</code>
     * @return The bytes for world.
     */
    com.google.protobuf.ByteString
        getWorldBytes();

    /**
     * <code>double x = 2 [json_name = "x"];</code>
     * @return The x.
     */
    double getX();

    /**
     * <code>double y = 3 [json_name = "y"];</code>
     * @return The y.
     */
    double getY();

    /**
     * <code>double z = 4 [json_name = "z"];</code>
     * @return The z.
     */
    double getZ();
  }
  /**
   * Protobuf type {@code lunarclient.apollo.common.v1.Location}
   */
  public static final class Location extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:lunarclient.apollo.common.v1.Location)
      LocationOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 1,
        /* suffix= */ "",
        Location.class.getName());
    }
    // Use Location.newBuilder() to construct.
    private Location(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Location() {
      world_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return lunarclient.apollo.common.v1.LocationOuterClass.internal_static_lunarclient_apollo_common_v1_Location_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return lunarclient.apollo.common.v1.LocationOuterClass.internal_static_lunarclient_apollo_common_v1_Location_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              lunarclient.apollo.common.v1.LocationOuterClass.Location.class, lunarclient.apollo.common.v1.LocationOuterClass.Location.Builder.class);
    }

    public static final int WORLD_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object world_ = "";
    /**
     * <code>string world = 1 [json_name = "world"];</code>
     * @return The world.
     */
    @java.lang.Override
    public java.lang.String getWorld() {
      java.lang.Object ref = world_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        world_ = s;
        return s;
      }
    }
    /**
     * <code>string world = 1 [json_name = "world"];</code>
     * @return The bytes for world.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getWorldBytes() {
      java.lang.Object ref = world_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        world_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int X_FIELD_NUMBER = 2;
    private double x_ = 0D;
    /**
     * <code>double x = 2 [json_name = "x"];</code>
     * @return The x.
     */
    @java.lang.Override
    public double getX() {
      return x_;
    }

    public static final int Y_FIELD_NUMBER = 3;
    private double y_ = 0D;
    /**
     * <code>double y = 3 [json_name = "y"];</code>
     * @return The y.
     */
    @java.lang.Override
    public double getY() {
      return y_;
    }

    public static final int Z_FIELD_NUMBER = 4;
    private double z_ = 0D;
    /**
     * <code>double z = 4 [json_name = "z"];</code>
     * @return The z.
     */
    @java.lang.Override
    public double getZ() {
      return z_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(world_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, world_);
      }
      if (java.lang.Double.doubleToRawLongBits(x_) != 0) {
        output.writeDouble(2, x_);
      }
      if (java.lang.Double.doubleToRawLongBits(y_) != 0) {
        output.writeDouble(3, y_);
      }
      if (java.lang.Double.doubleToRawLongBits(z_) != 0) {
        output.writeDouble(4, z_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(world_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, world_);
      }
      if (java.lang.Double.doubleToRawLongBits(x_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, x_);
      }
      if (java.lang.Double.doubleToRawLongBits(y_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, y_);
      }
      if (java.lang.Double.doubleToRawLongBits(z_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, z_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof lunarclient.apollo.common.v1.LocationOuterClass.Location)) {
        return super.equals(obj);
      }
      lunarclient.apollo.common.v1.LocationOuterClass.Location other = (lunarclient.apollo.common.v1.LocationOuterClass.Location) obj;

      if (!getWorld()
          .equals(other.getWorld())) return false;
      if (java.lang.Double.doubleToLongBits(getX())
          != java.lang.Double.doubleToLongBits(
              other.getX())) return false;
      if (java.lang.Double.doubleToLongBits(getY())
          != java.lang.Double.doubleToLongBits(
              other.getY())) return false;
      if (java.lang.Double.doubleToLongBits(getZ())
          != java.lang.Double.doubleToLongBits(
              other.getZ())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + WORLD_FIELD_NUMBER;
      hash = (53 * hash) + getWorld().hashCode();
      hash = (37 * hash) + X_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getX()));
      hash = (37 * hash) + Y_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getY()));
      hash = (37 * hash) + Z_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getZ()));
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static lunarclient.apollo.common.v1.LocationOuterClass.Location parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lunarclient.apollo.common.v1.LocationOuterClass.Location parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lunarclient.apollo.common.v1.LocationOuterClass.Location parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lunarclient.apollo.common.v1.LocationOuterClass.Location parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lunarclient.apollo.common.v1.LocationOuterClass.Location parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lunarclient.apollo.common.v1.LocationOuterClass.Location parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lunarclient.apollo.common.v1.LocationOuterClass.Location parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static lunarclient.apollo.common.v1.LocationOuterClass.Location parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static lunarclient.apollo.common.v1.LocationOuterClass.Location parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static lunarclient.apollo.common.v1.LocationOuterClass.Location parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static lunarclient.apollo.common.v1.LocationOuterClass.Location parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static lunarclient.apollo.common.v1.LocationOuterClass.Location parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(lunarclient.apollo.common.v1.LocationOuterClass.Location prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code lunarclient.apollo.common.v1.Location}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:lunarclient.apollo.common.v1.Location)
        lunarclient.apollo.common.v1.LocationOuterClass.LocationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return lunarclient.apollo.common.v1.LocationOuterClass.internal_static_lunarclient_apollo_common_v1_Location_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return lunarclient.apollo.common.v1.LocationOuterClass.internal_static_lunarclient_apollo_common_v1_Location_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                lunarclient.apollo.common.v1.LocationOuterClass.Location.class, lunarclient.apollo.common.v1.LocationOuterClass.Location.Builder.class);
      }

      // Construct using lunarclient.apollo.common.v1.LocationOuterClass.Location.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        world_ = "";
        x_ = 0D;
        y_ = 0D;
        z_ = 0D;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return lunarclient.apollo.common.v1.LocationOuterClass.internal_static_lunarclient_apollo_common_v1_Location_descriptor;
      }

      @java.lang.Override
      public lunarclient.apollo.common.v1.LocationOuterClass.Location getDefaultInstanceForType() {
        return lunarclient.apollo.common.v1.LocationOuterClass.Location.getDefaultInstance();
      }

      @java.lang.Override
      public lunarclient.apollo.common.v1.LocationOuterClass.Location build() {
        lunarclient.apollo.common.v1.LocationOuterClass.Location result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public lunarclient.apollo.common.v1.LocationOuterClass.Location buildPartial() {
        lunarclient.apollo.common.v1.LocationOuterClass.Location result = new lunarclient.apollo.common.v1.LocationOuterClass.Location(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(lunarclient.apollo.common.v1.LocationOuterClass.Location result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.world_ = world_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.x_ = x_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.y_ = y_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.z_ = z_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof lunarclient.apollo.common.v1.LocationOuterClass.Location) {
          return mergeFrom((lunarclient.apollo.common.v1.LocationOuterClass.Location)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(lunarclient.apollo.common.v1.LocationOuterClass.Location other) {
        if (other == lunarclient.apollo.common.v1.LocationOuterClass.Location.getDefaultInstance()) return this;
        if (!other.getWorld().isEmpty()) {
          world_ = other.world_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (java.lang.Double.doubleToRawLongBits(other.getX()) != 0) {
          setX(other.getX());
        }
        if (java.lang.Double.doubleToRawLongBits(other.getY()) != 0) {
          setY(other.getY());
        }
        if (java.lang.Double.doubleToRawLongBits(other.getZ()) != 0) {
          setZ(other.getZ());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                world_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 17: {
                x_ = input.readDouble();
                bitField0_ |= 0x00000002;
                break;
              } // case 17
              case 25: {
                y_ = input.readDouble();
                bitField0_ |= 0x00000004;
                break;
              } // case 25
              case 33: {
                z_ = input.readDouble();
                bitField0_ |= 0x00000008;
                break;
              } // case 33
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object world_ = "";
      /**
       * <code>string world = 1 [json_name = "world"];</code>
       * @return The world.
       */
      public java.lang.String getWorld() {
        java.lang.Object ref = world_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          world_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string world = 1 [json_name = "world"];</code>
       * @return The bytes for world.
       */
      public com.google.protobuf.ByteString
          getWorldBytes() {
        java.lang.Object ref = world_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          world_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string world = 1 [json_name = "world"];</code>
       * @param value The world to set.
       * @return This builder for chaining.
       */
      public Builder setWorld(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        world_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string world = 1 [json_name = "world"];</code>
       * @return This builder for chaining.
       */
      public Builder clearWorld() {
        world_ = getDefaultInstance().getWorld();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string world = 1 [json_name = "world"];</code>
       * @param value The bytes for world to set.
       * @return This builder for chaining.
       */
      public Builder setWorldBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        world_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private double x_ ;
      /**
       * <code>double x = 2 [json_name = "x"];</code>
       * @return The x.
       */
      @java.lang.Override
      public double getX() {
        return x_;
      }
      /**
       * <code>double x = 2 [json_name = "x"];</code>
       * @param value The x to set.
       * @return This builder for chaining.
       */
      public Builder setX(double value) {

        x_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>double x = 2 [json_name = "x"];</code>
       * @return This builder for chaining.
       */
      public Builder clearX() {
        bitField0_ = (bitField0_ & ~0x00000002);
        x_ = 0D;
        onChanged();
        return this;
      }

      private double y_ ;
      /**
       * <code>double y = 3 [json_name = "y"];</code>
       * @return The y.
       */
      @java.lang.Override
      public double getY() {
        return y_;
      }
      /**
       * <code>double y = 3 [json_name = "y"];</code>
       * @param value The y to set.
       * @return This builder for chaining.
       */
      public Builder setY(double value) {

        y_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>double y = 3 [json_name = "y"];</code>
       * @return This builder for chaining.
       */
      public Builder clearY() {
        bitField0_ = (bitField0_ & ~0x00000004);
        y_ = 0D;
        onChanged();
        return this;
      }

      private double z_ ;
      /**
       * <code>double z = 4 [json_name = "z"];</code>
       * @return The z.
       */
      @java.lang.Override
      public double getZ() {
        return z_;
      }
      /**
       * <code>double z = 4 [json_name = "z"];</code>
       * @param value The z to set.
       * @return This builder for chaining.
       */
      public Builder setZ(double value) {

        z_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>double z = 4 [json_name = "z"];</code>
       * @return This builder for chaining.
       */
      public Builder clearZ() {
        bitField0_ = (bitField0_ & ~0x00000008);
        z_ = 0D;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:lunarclient.apollo.common.v1.Location)
    }

    // @@protoc_insertion_point(class_scope:lunarclient.apollo.common.v1.Location)
    private static final lunarclient.apollo.common.v1.LocationOuterClass.Location DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new lunarclient.apollo.common.v1.LocationOuterClass.Location();
    }

    public static lunarclient.apollo.common.v1.LocationOuterClass.Location getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Location>
        PARSER = new com.google.protobuf.AbstractParser<Location>() {
      @java.lang.Override
      public Location parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Location> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Location> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public lunarclient.apollo.common.v1.LocationOuterClass.Location getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lunarclient_apollo_common_v1_BlockLocation_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lunarclient_apollo_common_v1_BlockLocation_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lunarclient_apollo_common_v1_PlayerLocation_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lunarclient_apollo_common_v1_PlayerLocation_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lunarclient_apollo_common_v1_Location_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lunarclient_apollo_common_v1_Location_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n+lunarclient/apollo/common/v1/location." +
      "proto\022\034lunarclient.apollo.common.v1\"O\n\rB" +
      "lockLocation\022\024\n\005world\030\001 \001(\tR\005world\022\014\n\001x\030" +
      "\002 \001(\021R\001x\022\014\n\001y\030\003 \001(\021R\001y\022\014\n\001z\030\004 \001(\021R\001z\"|\n\016" +
      "PlayerLocation\022B\n\010location\030\001 \001(\0132&.lunar" +
      "client.apollo.common.v1.LocationR\010locati" +
      "on\022\020\n\003yaw\030\002 \001(\002R\003yaw\022\024\n\005pitch\030\003 \001(\002R\005pit" +
      "ch\"J\n\010Location\022\024\n\005world\030\001 \001(\tR\005world\022\014\n\001" +
      "x\030\002 \001(\001R\001x\022\014\n\001y\030\003 \001(\001R\001y\022\014\n\001z\030\004 \001(\001R\001zb\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_lunarclient_apollo_common_v1_BlockLocation_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_lunarclient_apollo_common_v1_BlockLocation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lunarclient_apollo_common_v1_BlockLocation_descriptor,
        new java.lang.String[] { "World", "X", "Y", "Z", });
    internal_static_lunarclient_apollo_common_v1_PlayerLocation_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_lunarclient_apollo_common_v1_PlayerLocation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lunarclient_apollo_common_v1_PlayerLocation_descriptor,
        new java.lang.String[] { "Location", "Yaw", "Pitch", });
    internal_static_lunarclient_apollo_common_v1_Location_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_lunarclient_apollo_common_v1_Location_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lunarclient_apollo_common_v1_Location_descriptor,
        new java.lang.String[] { "World", "X", "Y", "Z", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
