// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: lunarclient/apollo/common/v1/sound.proto
// Protobuf Java Version: 4.31.1

package lunarclient.apollo.common.v1;

@com.google.protobuf.Generated
public final class SoundOuterClass {
  private SoundOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      SoundOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SimpleResourceLocationSoundOrBuilder extends
      // @@protoc_insertion_point(interface_extends:lunarclient.apollo.common.v1.SimpleResourceLocationSound)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string resource_location = 1 [json_name = "resourceLocation"];</code>
     * @return The resourceLocation.
     */
    java.lang.String getResourceLocation();
    /**
     * <code>string resource_location = 1 [json_name = "resourceLocation"];</code>
     * @return The bytes for resourceLocation.
     */
    com.google.protobuf.ByteString
        getResourceLocationBytes();
  }
  /**
   * Protobuf type {@code lunarclient.apollo.common.v1.SimpleResourceLocationSound}
   */
  public static final class SimpleResourceLocationSound extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:lunarclient.apollo.common.v1.SimpleResourceLocationSound)
      SimpleResourceLocationSoundOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 1,
        /* suffix= */ "",
        SimpleResourceLocationSound.class.getName());
    }
    // Use SimpleResourceLocationSound.newBuilder() to construct.
    private SimpleResourceLocationSound(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private SimpleResourceLocationSound() {
      resourceLocation_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return lunarclient.apollo.common.v1.SoundOuterClass.internal_static_lunarclient_apollo_common_v1_SimpleResourceLocationSound_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return lunarclient.apollo.common.v1.SoundOuterClass.internal_static_lunarclient_apollo_common_v1_SimpleResourceLocationSound_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              lunarclient.apollo.common.v1.SoundOuterClass.SimpleResourceLocationSound.class, lunarclient.apollo.common.v1.SoundOuterClass.SimpleResourceLocationSound.Builder.class);
    }

    public static final int RESOURCE_LOCATION_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object resourceLocation_ = "";
    /**
     * <code>string resource_location = 1 [json_name = "resourceLocation"];</code>
     * @return The resourceLocation.
     */
    @java.lang.Override
    public java.lang.String getResourceLocation() {
      java.lang.Object ref = resourceLocation_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        resourceLocation_ = s;
        return s;
      }
    }
    /**
     * <code>string resource_location = 1 [json_name = "resourceLocation"];</code>
     * @return The bytes for resourceLocation.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getResourceLocationBytes() {
      java.lang.Object ref = resourceLocation_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resourceLocation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(resourceLocation_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, resourceLocation_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(resourceLocation_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, resourceLocation_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof lunarclient.apollo.common.v1.SoundOuterClass.SimpleResourceLocationSound)) {
        return super.equals(obj);
      }
      lunarclient.apollo.common.v1.SoundOuterClass.SimpleResourceLocationSound other = (lunarclient.apollo.common.v1.SoundOuterClass.SimpleResourceLocationSound) obj;

      if (!getResourceLocation()
          .equals(other.getResourceLocation())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESOURCE_LOCATION_FIELD_NUMBER;
      hash = (53 * hash) + getResourceLocation().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static lunarclient.apollo.common.v1.SoundOuterClass.SimpleResourceLocationSound parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lunarclient.apollo.common.v1.SoundOuterClass.SimpleResourceLocationSound parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lunarclient.apollo.common.v1.SoundOuterClass.SimpleResourceLocationSound parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lunarclient.apollo.common.v1.SoundOuterClass.SimpleResourceLocationSound parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lunarclient.apollo.common.v1.SoundOuterClass.SimpleResourceLocationSound parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lunarclient.apollo.common.v1.SoundOuterClass.SimpleResourceLocationSound parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lunarclient.apollo.common.v1.SoundOuterClass.SimpleResourceLocationSound parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static lunarclient.apollo.common.v1.SoundOuterClass.SimpleResourceLocationSound parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static lunarclient.apollo.common.v1.SoundOuterClass.SimpleResourceLocationSound parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static lunarclient.apollo.common.v1.SoundOuterClass.SimpleResourceLocationSound parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static lunarclient.apollo.common.v1.SoundOuterClass.SimpleResourceLocationSound parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static lunarclient.apollo.common.v1.SoundOuterClass.SimpleResourceLocationSound parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(lunarclient.apollo.common.v1.SoundOuterClass.SimpleResourceLocationSound prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code lunarclient.apollo.common.v1.SimpleResourceLocationSound}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:lunarclient.apollo.common.v1.SimpleResourceLocationSound)
        lunarclient.apollo.common.v1.SoundOuterClass.SimpleResourceLocationSoundOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return lunarclient.apollo.common.v1.SoundOuterClass.internal_static_lunarclient_apollo_common_v1_SimpleResourceLocationSound_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return lunarclient.apollo.common.v1.SoundOuterClass.internal_static_lunarclient_apollo_common_v1_SimpleResourceLocationSound_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                lunarclient.apollo.common.v1.SoundOuterClass.SimpleResourceLocationSound.class, lunarclient.apollo.common.v1.SoundOuterClass.SimpleResourceLocationSound.Builder.class);
      }

      // Construct using lunarclient.apollo.common.v1.SoundOuterClass.SimpleResourceLocationSound.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        resourceLocation_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return lunarclient.apollo.common.v1.SoundOuterClass.internal_static_lunarclient_apollo_common_v1_SimpleResourceLocationSound_descriptor;
      }

      @java.lang.Override
      public lunarclient.apollo.common.v1.SoundOuterClass.SimpleResourceLocationSound getDefaultInstanceForType() {
        return lunarclient.apollo.common.v1.SoundOuterClass.SimpleResourceLocationSound.getDefaultInstance();
      }

      @java.lang.Override
      public lunarclient.apollo.common.v1.SoundOuterClass.SimpleResourceLocationSound build() {
        lunarclient.apollo.common.v1.SoundOuterClass.SimpleResourceLocationSound result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public lunarclient.apollo.common.v1.SoundOuterClass.SimpleResourceLocationSound buildPartial() {
        lunarclient.apollo.common.v1.SoundOuterClass.SimpleResourceLocationSound result = new lunarclient.apollo.common.v1.SoundOuterClass.SimpleResourceLocationSound(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(lunarclient.apollo.common.v1.SoundOuterClass.SimpleResourceLocationSound result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.resourceLocation_ = resourceLocation_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof lunarclient.apollo.common.v1.SoundOuterClass.SimpleResourceLocationSound) {
          return mergeFrom((lunarclient.apollo.common.v1.SoundOuterClass.SimpleResourceLocationSound)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(lunarclient.apollo.common.v1.SoundOuterClass.SimpleResourceLocationSound other) {
        if (other == lunarclient.apollo.common.v1.SoundOuterClass.SimpleResourceLocationSound.getDefaultInstance()) return this;
        if (!other.getResourceLocation().isEmpty()) {
          resourceLocation_ = other.resourceLocation_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                resourceLocation_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object resourceLocation_ = "";
      /**
       * <code>string resource_location = 1 [json_name = "resourceLocation"];</code>
       * @return The resourceLocation.
       */
      public java.lang.String getResourceLocation() {
        java.lang.Object ref = resourceLocation_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          resourceLocation_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string resource_location = 1 [json_name = "resourceLocation"];</code>
       * @return The bytes for resourceLocation.
       */
      public com.google.protobuf.ByteString
          getResourceLocationBytes() {
        java.lang.Object ref = resourceLocation_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          resourceLocation_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string resource_location = 1 [json_name = "resourceLocation"];</code>
       * @param value The resourceLocation to set.
       * @return This builder for chaining.
       */
      public Builder setResourceLocation(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        resourceLocation_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string resource_location = 1 [json_name = "resourceLocation"];</code>
       * @return This builder for chaining.
       */
      public Builder clearResourceLocation() {
        resourceLocation_ = getDefaultInstance().getResourceLocation();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string resource_location = 1 [json_name = "resourceLocation"];</code>
       * @param value The bytes for resourceLocation to set.
       * @return This builder for chaining.
       */
      public Builder setResourceLocationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        resourceLocation_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:lunarclient.apollo.common.v1.SimpleResourceLocationSound)
    }

    // @@protoc_insertion_point(class_scope:lunarclient.apollo.common.v1.SimpleResourceLocationSound)
    private static final lunarclient.apollo.common.v1.SoundOuterClass.SimpleResourceLocationSound DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new lunarclient.apollo.common.v1.SoundOuterClass.SimpleResourceLocationSound();
    }

    public static lunarclient.apollo.common.v1.SoundOuterClass.SimpleResourceLocationSound getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SimpleResourceLocationSound>
        PARSER = new com.google.protobuf.AbstractParser<SimpleResourceLocationSound>() {
      @java.lang.Override
      public SimpleResourceLocationSound parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<SimpleResourceLocationSound> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SimpleResourceLocationSound> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public lunarclient.apollo.common.v1.SoundOuterClass.SimpleResourceLocationSound getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SoundOrBuilder extends
      // @@protoc_insertion_point(interface_extends:lunarclient.apollo.common.v1.Sound)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.lunarclient.apollo.common.v1.SimpleResourceLocationSound simple_resource_location = 1 [json_name = "simpleResourceLocation"];</code>
     * @return Whether the simpleResourceLocation field is set.
     */
    boolean hasSimpleResourceLocation();
    /**
     * <code>.lunarclient.apollo.common.v1.SimpleResourceLocationSound simple_resource_location = 1 [json_name = "simpleResourceLocation"];</code>
     * @return The simpleResourceLocation.
     */
    lunarclient.apollo.common.v1.SoundOuterClass.SimpleResourceLocationSound getSimpleResourceLocation();
    /**
     * <code>.lunarclient.apollo.common.v1.SimpleResourceLocationSound simple_resource_location = 1 [json_name = "simpleResourceLocation"];</code>
     */
    lunarclient.apollo.common.v1.SoundOuterClass.SimpleResourceLocationSoundOrBuilder getSimpleResourceLocationOrBuilder();

    lunarclient.apollo.common.v1.SoundOuterClass.Sound.ContentsCase getContentsCase();
  }
  /**
   * Protobuf type {@code lunarclient.apollo.common.v1.Sound}
   */
  public static final class Sound extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:lunarclient.apollo.common.v1.Sound)
      SoundOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 1,
        /* suffix= */ "",
        Sound.class.getName());
    }
    // Use Sound.newBuilder() to construct.
    private Sound(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Sound() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return lunarclient.apollo.common.v1.SoundOuterClass.internal_static_lunarclient_apollo_common_v1_Sound_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return lunarclient.apollo.common.v1.SoundOuterClass.internal_static_lunarclient_apollo_common_v1_Sound_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              lunarclient.apollo.common.v1.SoundOuterClass.Sound.class, lunarclient.apollo.common.v1.SoundOuterClass.Sound.Builder.class);
    }

    private int contentsCase_ = 0;
    @SuppressWarnings("serial")
    private java.lang.Object contents_;
    public enum ContentsCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      SIMPLE_RESOURCE_LOCATION(1),
      CONTENTS_NOT_SET(0);
      private final int value;
      private ContentsCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static ContentsCase valueOf(int value) {
        return forNumber(value);
      }

      public static ContentsCase forNumber(int value) {
        switch (value) {
          case 1: return SIMPLE_RESOURCE_LOCATION;
          case 0: return CONTENTS_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public ContentsCase
    getContentsCase() {
      return ContentsCase.forNumber(
          contentsCase_);
    }

    public static final int SIMPLE_RESOURCE_LOCATION_FIELD_NUMBER = 1;
    /**
     * <code>.lunarclient.apollo.common.v1.SimpleResourceLocationSound simple_resource_location = 1 [json_name = "simpleResourceLocation"];</code>
     * @return Whether the simpleResourceLocation field is set.
     */
    @java.lang.Override
    public boolean hasSimpleResourceLocation() {
      return contentsCase_ == 1;
    }
    /**
     * <code>.lunarclient.apollo.common.v1.SimpleResourceLocationSound simple_resource_location = 1 [json_name = "simpleResourceLocation"];</code>
     * @return The simpleResourceLocation.
     */
    @java.lang.Override
    public lunarclient.apollo.common.v1.SoundOuterClass.SimpleResourceLocationSound getSimpleResourceLocation() {
      if (contentsCase_ == 1) {
         return (lunarclient.apollo.common.v1.SoundOuterClass.SimpleResourceLocationSound) contents_;
      }
      return lunarclient.apollo.common.v1.SoundOuterClass.SimpleResourceLocationSound.getDefaultInstance();
    }
    /**
     * <code>.lunarclient.apollo.common.v1.SimpleResourceLocationSound simple_resource_location = 1 [json_name = "simpleResourceLocation"];</code>
     */
    @java.lang.Override
    public lunarclient.apollo.common.v1.SoundOuterClass.SimpleResourceLocationSoundOrBuilder getSimpleResourceLocationOrBuilder() {
      if (contentsCase_ == 1) {
         return (lunarclient.apollo.common.v1.SoundOuterClass.SimpleResourceLocationSound) contents_;
      }
      return lunarclient.apollo.common.v1.SoundOuterClass.SimpleResourceLocationSound.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (contentsCase_ == 1) {
        output.writeMessage(1, (lunarclient.apollo.common.v1.SoundOuterClass.SimpleResourceLocationSound) contents_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (contentsCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (lunarclient.apollo.common.v1.SoundOuterClass.SimpleResourceLocationSound) contents_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof lunarclient.apollo.common.v1.SoundOuterClass.Sound)) {
        return super.equals(obj);
      }
      lunarclient.apollo.common.v1.SoundOuterClass.Sound other = (lunarclient.apollo.common.v1.SoundOuterClass.Sound) obj;

      if (!getContentsCase().equals(other.getContentsCase())) return false;
      switch (contentsCase_) {
        case 1:
          if (!getSimpleResourceLocation()
              .equals(other.getSimpleResourceLocation())) return false;
          break;
        case 0:
        default:
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      switch (contentsCase_) {
        case 1:
          hash = (37 * hash) + SIMPLE_RESOURCE_LOCATION_FIELD_NUMBER;
          hash = (53 * hash) + getSimpleResourceLocation().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static lunarclient.apollo.common.v1.SoundOuterClass.Sound parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lunarclient.apollo.common.v1.SoundOuterClass.Sound parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lunarclient.apollo.common.v1.SoundOuterClass.Sound parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lunarclient.apollo.common.v1.SoundOuterClass.Sound parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lunarclient.apollo.common.v1.SoundOuterClass.Sound parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lunarclient.apollo.common.v1.SoundOuterClass.Sound parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lunarclient.apollo.common.v1.SoundOuterClass.Sound parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static lunarclient.apollo.common.v1.SoundOuterClass.Sound parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static lunarclient.apollo.common.v1.SoundOuterClass.Sound parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static lunarclient.apollo.common.v1.SoundOuterClass.Sound parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static lunarclient.apollo.common.v1.SoundOuterClass.Sound parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static lunarclient.apollo.common.v1.SoundOuterClass.Sound parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(lunarclient.apollo.common.v1.SoundOuterClass.Sound prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code lunarclient.apollo.common.v1.Sound}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:lunarclient.apollo.common.v1.Sound)
        lunarclient.apollo.common.v1.SoundOuterClass.SoundOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return lunarclient.apollo.common.v1.SoundOuterClass.internal_static_lunarclient_apollo_common_v1_Sound_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return lunarclient.apollo.common.v1.SoundOuterClass.internal_static_lunarclient_apollo_common_v1_Sound_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                lunarclient.apollo.common.v1.SoundOuterClass.Sound.class, lunarclient.apollo.common.v1.SoundOuterClass.Sound.Builder.class);
      }

      // Construct using lunarclient.apollo.common.v1.SoundOuterClass.Sound.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (simpleResourceLocationBuilder_ != null) {
          simpleResourceLocationBuilder_.clear();
        }
        contentsCase_ = 0;
        contents_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return lunarclient.apollo.common.v1.SoundOuterClass.internal_static_lunarclient_apollo_common_v1_Sound_descriptor;
      }

      @java.lang.Override
      public lunarclient.apollo.common.v1.SoundOuterClass.Sound getDefaultInstanceForType() {
        return lunarclient.apollo.common.v1.SoundOuterClass.Sound.getDefaultInstance();
      }

      @java.lang.Override
      public lunarclient.apollo.common.v1.SoundOuterClass.Sound build() {
        lunarclient.apollo.common.v1.SoundOuterClass.Sound result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public lunarclient.apollo.common.v1.SoundOuterClass.Sound buildPartial() {
        lunarclient.apollo.common.v1.SoundOuterClass.Sound result = new lunarclient.apollo.common.v1.SoundOuterClass.Sound(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        buildPartialOneofs(result);
        onBuilt();
        return result;
      }

      private void buildPartial0(lunarclient.apollo.common.v1.SoundOuterClass.Sound result) {
        int from_bitField0_ = bitField0_;
      }

      private void buildPartialOneofs(lunarclient.apollo.common.v1.SoundOuterClass.Sound result) {
        result.contentsCase_ = contentsCase_;
        result.contents_ = this.contents_;
        if (contentsCase_ == 1 &&
            simpleResourceLocationBuilder_ != null) {
          result.contents_ = simpleResourceLocationBuilder_.build();
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof lunarclient.apollo.common.v1.SoundOuterClass.Sound) {
          return mergeFrom((lunarclient.apollo.common.v1.SoundOuterClass.Sound)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(lunarclient.apollo.common.v1.SoundOuterClass.Sound other) {
        if (other == lunarclient.apollo.common.v1.SoundOuterClass.Sound.getDefaultInstance()) return this;
        switch (other.getContentsCase()) {
          case SIMPLE_RESOURCE_LOCATION: {
            mergeSimpleResourceLocation(other.getSimpleResourceLocation());
            break;
          }
          case CONTENTS_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    internalGetSimpleResourceLocationFieldBuilder().getBuilder(),
                    extensionRegistry);
                contentsCase_ = 1;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int contentsCase_ = 0;
      private java.lang.Object contents_;
      public ContentsCase
          getContentsCase() {
        return ContentsCase.forNumber(
            contentsCase_);
      }

      public Builder clearContents() {
        contentsCase_ = 0;
        contents_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private com.google.protobuf.SingleFieldBuilder<
          lunarclient.apollo.common.v1.SoundOuterClass.SimpleResourceLocationSound, lunarclient.apollo.common.v1.SoundOuterClass.SimpleResourceLocationSound.Builder, lunarclient.apollo.common.v1.SoundOuterClass.SimpleResourceLocationSoundOrBuilder> simpleResourceLocationBuilder_;
      /**
       * <code>.lunarclient.apollo.common.v1.SimpleResourceLocationSound simple_resource_location = 1 [json_name = "simpleResourceLocation"];</code>
       * @return Whether the simpleResourceLocation field is set.
       */
      @java.lang.Override
      public boolean hasSimpleResourceLocation() {
        return contentsCase_ == 1;
      }
      /**
       * <code>.lunarclient.apollo.common.v1.SimpleResourceLocationSound simple_resource_location = 1 [json_name = "simpleResourceLocation"];</code>
       * @return The simpleResourceLocation.
       */
      @java.lang.Override
      public lunarclient.apollo.common.v1.SoundOuterClass.SimpleResourceLocationSound getSimpleResourceLocation() {
        if (simpleResourceLocationBuilder_ == null) {
          if (contentsCase_ == 1) {
            return (lunarclient.apollo.common.v1.SoundOuterClass.SimpleResourceLocationSound) contents_;
          }
          return lunarclient.apollo.common.v1.SoundOuterClass.SimpleResourceLocationSound.getDefaultInstance();
        } else {
          if (contentsCase_ == 1) {
            return simpleResourceLocationBuilder_.getMessage();
          }
          return lunarclient.apollo.common.v1.SoundOuterClass.SimpleResourceLocationSound.getDefaultInstance();
        }
      }
      /**
       * <code>.lunarclient.apollo.common.v1.SimpleResourceLocationSound simple_resource_location = 1 [json_name = "simpleResourceLocation"];</code>
       */
      public Builder setSimpleResourceLocation(lunarclient.apollo.common.v1.SoundOuterClass.SimpleResourceLocationSound value) {
        if (simpleResourceLocationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          contents_ = value;
          onChanged();
        } else {
          simpleResourceLocationBuilder_.setMessage(value);
        }
        contentsCase_ = 1;
        return this;
      }
      /**
       * <code>.lunarclient.apollo.common.v1.SimpleResourceLocationSound simple_resource_location = 1 [json_name = "simpleResourceLocation"];</code>
       */
      public Builder setSimpleResourceLocation(
          lunarclient.apollo.common.v1.SoundOuterClass.SimpleResourceLocationSound.Builder builderForValue) {
        if (simpleResourceLocationBuilder_ == null) {
          contents_ = builderForValue.build();
          onChanged();
        } else {
          simpleResourceLocationBuilder_.setMessage(builderForValue.build());
        }
        contentsCase_ = 1;
        return this;
      }
      /**
       * <code>.lunarclient.apollo.common.v1.SimpleResourceLocationSound simple_resource_location = 1 [json_name = "simpleResourceLocation"];</code>
       */
      public Builder mergeSimpleResourceLocation(lunarclient.apollo.common.v1.SoundOuterClass.SimpleResourceLocationSound value) {
        if (simpleResourceLocationBuilder_ == null) {
          if (contentsCase_ == 1 &&
              contents_ != lunarclient.apollo.common.v1.SoundOuterClass.SimpleResourceLocationSound.getDefaultInstance()) {
            contents_ = lunarclient.apollo.common.v1.SoundOuterClass.SimpleResourceLocationSound.newBuilder((lunarclient.apollo.common.v1.SoundOuterClass.SimpleResourceLocationSound) contents_)
                .mergeFrom(value).buildPartial();
          } else {
            contents_ = value;
          }
          onChanged();
        } else {
          if (contentsCase_ == 1) {
            simpleResourceLocationBuilder_.mergeFrom(value);
          } else {
            simpleResourceLocationBuilder_.setMessage(value);
          }
        }
        contentsCase_ = 1;
        return this;
      }
      /**
       * <code>.lunarclient.apollo.common.v1.SimpleResourceLocationSound simple_resource_location = 1 [json_name = "simpleResourceLocation"];</code>
       */
      public Builder clearSimpleResourceLocation() {
        if (simpleResourceLocationBuilder_ == null) {
          if (contentsCase_ == 1) {
            contentsCase_ = 0;
            contents_ = null;
            onChanged();
          }
        } else {
          if (contentsCase_ == 1) {
            contentsCase_ = 0;
            contents_ = null;
          }
          simpleResourceLocationBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.lunarclient.apollo.common.v1.SimpleResourceLocationSound simple_resource_location = 1 [json_name = "simpleResourceLocation"];</code>
       */
      public lunarclient.apollo.common.v1.SoundOuterClass.SimpleResourceLocationSound.Builder getSimpleResourceLocationBuilder() {
        return internalGetSimpleResourceLocationFieldBuilder().getBuilder();
      }
      /**
       * <code>.lunarclient.apollo.common.v1.SimpleResourceLocationSound simple_resource_location = 1 [json_name = "simpleResourceLocation"];</code>
       */
      @java.lang.Override
      public lunarclient.apollo.common.v1.SoundOuterClass.SimpleResourceLocationSoundOrBuilder getSimpleResourceLocationOrBuilder() {
        if ((contentsCase_ == 1) && (simpleResourceLocationBuilder_ != null)) {
          return simpleResourceLocationBuilder_.getMessageOrBuilder();
        } else {
          if (contentsCase_ == 1) {
            return (lunarclient.apollo.common.v1.SoundOuterClass.SimpleResourceLocationSound) contents_;
          }
          return lunarclient.apollo.common.v1.SoundOuterClass.SimpleResourceLocationSound.getDefaultInstance();
        }
      }
      /**
       * <code>.lunarclient.apollo.common.v1.SimpleResourceLocationSound simple_resource_location = 1 [json_name = "simpleResourceLocation"];</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          lunarclient.apollo.common.v1.SoundOuterClass.SimpleResourceLocationSound, lunarclient.apollo.common.v1.SoundOuterClass.SimpleResourceLocationSound.Builder, lunarclient.apollo.common.v1.SoundOuterClass.SimpleResourceLocationSoundOrBuilder> 
          internalGetSimpleResourceLocationFieldBuilder() {
        if (simpleResourceLocationBuilder_ == null) {
          if (!(contentsCase_ == 1)) {
            contents_ = lunarclient.apollo.common.v1.SoundOuterClass.SimpleResourceLocationSound.getDefaultInstance();
          }
          simpleResourceLocationBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              lunarclient.apollo.common.v1.SoundOuterClass.SimpleResourceLocationSound, lunarclient.apollo.common.v1.SoundOuterClass.SimpleResourceLocationSound.Builder, lunarclient.apollo.common.v1.SoundOuterClass.SimpleResourceLocationSoundOrBuilder>(
                  (lunarclient.apollo.common.v1.SoundOuterClass.SimpleResourceLocationSound) contents_,
                  getParentForChildren(),
                  isClean());
          contents_ = null;
        }
        contentsCase_ = 1;
        onChanged();
        return simpleResourceLocationBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:lunarclient.apollo.common.v1.Sound)
    }

    // @@protoc_insertion_point(class_scope:lunarclient.apollo.common.v1.Sound)
    private static final lunarclient.apollo.common.v1.SoundOuterClass.Sound DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new lunarclient.apollo.common.v1.SoundOuterClass.Sound();
    }

    public static lunarclient.apollo.common.v1.SoundOuterClass.Sound getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Sound>
        PARSER = new com.google.protobuf.AbstractParser<Sound>() {
      @java.lang.Override
      public Sound parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Sound> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Sound> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public lunarclient.apollo.common.v1.SoundOuterClass.Sound getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lunarclient_apollo_common_v1_SimpleResourceLocationSound_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lunarclient_apollo_common_v1_SimpleResourceLocationSound_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lunarclient_apollo_common_v1_Sound_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lunarclient_apollo_common_v1_Sound_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n(lunarclient/apollo/common/v1/sound.pro" +
      "to\022\034lunarclient.apollo.common.v1\"J\n\033Simp" +
      "leResourceLocationSound\022+\n\021resource_loca" +
      "tion\030\001 \001(\tR\020resourceLocation\"\212\001\n\005Sound\022u" +
      "\n\030simple_resource_location\030\001 \001(\01329.lunar" +
      "client.apollo.common.v1.SimpleResourceLo" +
      "cationSoundH\000R\026simpleResourceLocationB\n\n" +
      "\010contentsb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_lunarclient_apollo_common_v1_SimpleResourceLocationSound_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_lunarclient_apollo_common_v1_SimpleResourceLocationSound_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lunarclient_apollo_common_v1_SimpleResourceLocationSound_descriptor,
        new java.lang.String[] { "ResourceLocation", });
    internal_static_lunarclient_apollo_common_v1_Sound_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_lunarclient_apollo_common_v1_Sound_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lunarclient_apollo_common_v1_Sound_descriptor,
        new java.lang.String[] { "SimpleResourceLocation", "Contents", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
