// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: lunarclient/apollo/common/v1/uuid.proto
// Protobuf Java Version: 4.31.1

package lunarclient.apollo.common.v1;

@com.google.protobuf.Generated
public final class UuidOuterClass {
  private UuidOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      UuidOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UuidOrBuilder extends
      // @@protoc_insertion_point(interface_extends:lunarclient.apollo.common.v1.Uuid)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Upper 64 bits of this UUID.
     * </pre>
     *
     * <code>fixed64 high64 = 1 [json_name = "high64"];</code>
     * @return The high64.
     */
    long getHigh64();

    /**
     * <pre>
     * Lower 64 bits of this UUID.
     * </pre>
     *
     * <code>fixed64 low64 = 2 [json_name = "low64"];</code>
     * @return The low64.
     */
    long getLow64();
  }
  /**
   * <pre>
   * A wrapper around a UUID, primarily used to uniquely identify a Minecraft player.
   * This encoding should be used *in all cases*, and is favored over a String encoding
   * (such as uuid.toString()), sending as bytes, or any other way to encode a UUID.
   *
   * In Java, this can be created via:
   *
   * Uuid.newBuilder()
   * .setHigh64(uuid.getMostSignificantBits())
   * .setLow64(uuid.getLeastSignificantBits())
   * .build();
   *
   * where "uuid" is a java.util.UUID
   *
   * and this message can be converted back to a java.util.UUID via:
   *
   * new UUID(uuid.getHigh64(), uuid.getLow64());
   * </pre>
   *
   * Protobuf type {@code lunarclient.apollo.common.v1.Uuid}
   */
  public static final class Uuid extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:lunarclient.apollo.common.v1.Uuid)
      UuidOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 1,
        /* suffix= */ "",
        Uuid.class.getName());
    }
    // Use Uuid.newBuilder() to construct.
    private Uuid(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Uuid() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return lunarclient.apollo.common.v1.UuidOuterClass.internal_static_lunarclient_apollo_common_v1_Uuid_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return lunarclient.apollo.common.v1.UuidOuterClass.internal_static_lunarclient_apollo_common_v1_Uuid_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              lunarclient.apollo.common.v1.UuidOuterClass.Uuid.class, lunarclient.apollo.common.v1.UuidOuterClass.Uuid.Builder.class);
    }

    public static final int HIGH64_FIELD_NUMBER = 1;
    private long high64_ = 0L;
    /**
     * <pre>
     * Upper 64 bits of this UUID.
     * </pre>
     *
     * <code>fixed64 high64 = 1 [json_name = "high64"];</code>
     * @return The high64.
     */
    @java.lang.Override
    public long getHigh64() {
      return high64_;
    }

    public static final int LOW64_FIELD_NUMBER = 2;
    private long low64_ = 0L;
    /**
     * <pre>
     * Lower 64 bits of this UUID.
     * </pre>
     *
     * <code>fixed64 low64 = 2 [json_name = "low64"];</code>
     * @return The low64.
     */
    @java.lang.Override
    public long getLow64() {
      return low64_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (high64_ != 0L) {
        output.writeFixed64(1, high64_);
      }
      if (low64_ != 0L) {
        output.writeFixed64(2, low64_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (high64_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(1, high64_);
      }
      if (low64_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(2, low64_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof lunarclient.apollo.common.v1.UuidOuterClass.Uuid)) {
        return super.equals(obj);
      }
      lunarclient.apollo.common.v1.UuidOuterClass.Uuid other = (lunarclient.apollo.common.v1.UuidOuterClass.Uuid) obj;

      if (getHigh64()
          != other.getHigh64()) return false;
      if (getLow64()
          != other.getLow64()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + HIGH64_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getHigh64());
      hash = (37 * hash) + LOW64_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLow64());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static lunarclient.apollo.common.v1.UuidOuterClass.Uuid parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lunarclient.apollo.common.v1.UuidOuterClass.Uuid parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lunarclient.apollo.common.v1.UuidOuterClass.Uuid parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lunarclient.apollo.common.v1.UuidOuterClass.Uuid parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lunarclient.apollo.common.v1.UuidOuterClass.Uuid parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lunarclient.apollo.common.v1.UuidOuterClass.Uuid parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lunarclient.apollo.common.v1.UuidOuterClass.Uuid parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static lunarclient.apollo.common.v1.UuidOuterClass.Uuid parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static lunarclient.apollo.common.v1.UuidOuterClass.Uuid parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static lunarclient.apollo.common.v1.UuidOuterClass.Uuid parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static lunarclient.apollo.common.v1.UuidOuterClass.Uuid parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static lunarclient.apollo.common.v1.UuidOuterClass.Uuid parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(lunarclient.apollo.common.v1.UuidOuterClass.Uuid prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }


    /**
     * <pre>
     * A wrapper around a UUID, primarily used to uniquely identify a Minecraft player.
     * This encoding should be used *in all cases*, and is favored over a String encoding
     * (such as uuid.toString()), sending as bytes, or any other way to encode a UUID.
     *
     * In Java, this can be created via:
     *
     * Uuid.newBuilder()
     * .setHigh64(uuid.getMostSignificantBits())
     * .setLow64(uuid.getLeastSignificantBits())
     * .build();
     *
     * where "uuid" is a java.util.UUID
     *
     * and this message can be converted back to a java.util.UUID via:
     *
     * new UUID(uuid.getHigh64(), uuid.getLow64());
     * </pre>
     *
     * Protobuf type {@code lunarclient.apollo.common.v1.Uuid}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:lunarclient.apollo.common.v1.Uuid)
        lunarclient.apollo.common.v1.UuidOuterClass.UuidOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return lunarclient.apollo.common.v1.UuidOuterClass.internal_static_lunarclient_apollo_common_v1_Uuid_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return lunarclient.apollo.common.v1.UuidOuterClass.internal_static_lunarclient_apollo_common_v1_Uuid_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                lunarclient.apollo.common.v1.UuidOuterClass.Uuid.class, lunarclient.apollo.common.v1.UuidOuterClass.Uuid.Builder.class);
      }

      // Construct using lunarclient.apollo.common.v1.UuidOuterClass.Uuid.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        high64_ = 0L;
        low64_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return lunarclient.apollo.common.v1.UuidOuterClass.internal_static_lunarclient_apollo_common_v1_Uuid_descriptor;
      }

      @java.lang.Override
      public lunarclient.apollo.common.v1.UuidOuterClass.Uuid getDefaultInstanceForType() {
        return lunarclient.apollo.common.v1.UuidOuterClass.Uuid.getDefaultInstance();
      }

      @java.lang.Override
      public lunarclient.apollo.common.v1.UuidOuterClass.Uuid build() {
        lunarclient.apollo.common.v1.UuidOuterClass.Uuid result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public lunarclient.apollo.common.v1.UuidOuterClass.Uuid buildPartial() {
        lunarclient.apollo.common.v1.UuidOuterClass.Uuid result = new lunarclient.apollo.common.v1.UuidOuterClass.Uuid(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(lunarclient.apollo.common.v1.UuidOuterClass.Uuid result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.high64_ = high64_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.low64_ = low64_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof lunarclient.apollo.common.v1.UuidOuterClass.Uuid) {
          return mergeFrom((lunarclient.apollo.common.v1.UuidOuterClass.Uuid)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(lunarclient.apollo.common.v1.UuidOuterClass.Uuid other) {
        if (other == lunarclient.apollo.common.v1.UuidOuterClass.Uuid.getDefaultInstance()) return this;
        if (other.getHigh64() != 0L) {
          setHigh64(other.getHigh64());
        }
        if (other.getLow64() != 0L) {
          setLow64(other.getLow64());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 9: {
                high64_ = input.readFixed64();
                bitField0_ |= 0x00000001;
                break;
              } // case 9
              case 17: {
                low64_ = input.readFixed64();
                bitField0_ |= 0x00000002;
                break;
              } // case 17
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long high64_ ;
      /**
       * <pre>
       * Upper 64 bits of this UUID.
       * </pre>
       *
       * <code>fixed64 high64 = 1 [json_name = "high64"];</code>
       * @return The high64.
       */
      @java.lang.Override
      public long getHigh64() {
        return high64_;
      }
      /**
       * <pre>
       * Upper 64 bits of this UUID.
       * </pre>
       *
       * <code>fixed64 high64 = 1 [json_name = "high64"];</code>
       * @param value The high64 to set.
       * @return This builder for chaining.
       */
      public Builder setHigh64(long value) {

        high64_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Upper 64 bits of this UUID.
       * </pre>
       *
       * <code>fixed64 high64 = 1 [json_name = "high64"];</code>
       * @return This builder for chaining.
       */
      public Builder clearHigh64() {
        bitField0_ = (bitField0_ & ~0x00000001);
        high64_ = 0L;
        onChanged();
        return this;
      }

      private long low64_ ;
      /**
       * <pre>
       * Lower 64 bits of this UUID.
       * </pre>
       *
       * <code>fixed64 low64 = 2 [json_name = "low64"];</code>
       * @return The low64.
       */
      @java.lang.Override
      public long getLow64() {
        return low64_;
      }
      /**
       * <pre>
       * Lower 64 bits of this UUID.
       * </pre>
       *
       * <code>fixed64 low64 = 2 [json_name = "low64"];</code>
       * @param value The low64 to set.
       * @return This builder for chaining.
       */
      public Builder setLow64(long value) {

        low64_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Lower 64 bits of this UUID.
       * </pre>
       *
       * <code>fixed64 low64 = 2 [json_name = "low64"];</code>
       * @return This builder for chaining.
       */
      public Builder clearLow64() {
        bitField0_ = (bitField0_ & ~0x00000002);
        low64_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:lunarclient.apollo.common.v1.Uuid)
    }

    // @@protoc_insertion_point(class_scope:lunarclient.apollo.common.v1.Uuid)
    private static final lunarclient.apollo.common.v1.UuidOuterClass.Uuid DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new lunarclient.apollo.common.v1.UuidOuterClass.Uuid();
    }

    public static lunarclient.apollo.common.v1.UuidOuterClass.Uuid getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Uuid>
        PARSER = new com.google.protobuf.AbstractParser<Uuid>() {
      @java.lang.Override
      public Uuid parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Uuid> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Uuid> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public lunarclient.apollo.common.v1.UuidOuterClass.Uuid getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lunarclient_apollo_common_v1_Uuid_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lunarclient_apollo_common_v1_Uuid_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\'lunarclient/apollo/common/v1/uuid.prot" +
      "o\022\034lunarclient.apollo.common.v1\"4\n\004Uuid\022" +
      "\026\n\006high64\030\001 \001(\006R\006high64\022\024\n\005low64\030\002 \001(\006R\005" +
      "low64b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_lunarclient_apollo_common_v1_Uuid_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_lunarclient_apollo_common_v1_Uuid_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lunarclient_apollo_common_v1_Uuid_descriptor,
        new java.lang.String[] { "High64", "Low64", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
