// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: lunarclient/apollo/common/v1/version.proto
// Protobuf Java Version: 4.31.1

package lunarclient.apollo.common.v1;

@com.google.protobuf.Generated
public final class Version {
  private Version() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      Version.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MinecraftVersionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:lunarclient.apollo.common.v1.MinecraftVersion)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * The enum encoding of this version. For example, "v1_8_9"
     * </pre>
     *
     * <code>string enum = 1 [json_name = "enum"];</code>
     * @return The enum.
     */
    java.lang.String getEnum();
    /**
     * <pre>
     * The enum encoding of this version. For example, "v1_8_9"
     * </pre>
     *
     * <code>string enum = 1 [json_name = "enum"];</code>
     * @return The bytes for enum.
     */
    com.google.protobuf.ByteString
        getEnumBytes();
  }
  /**
   * <pre>
   * A reference to a specific version (released by Mojang) of Minecraft.
   * For example, Minecraft 1.8.9, or 1.19.4
   * </pre>
   *
   * Protobuf type {@code lunarclient.apollo.common.v1.MinecraftVersion}
   */
  public static final class MinecraftVersion extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:lunarclient.apollo.common.v1.MinecraftVersion)
      MinecraftVersionOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 1,
        /* suffix= */ "",
        MinecraftVersion.class.getName());
    }
    // Use MinecraftVersion.newBuilder() to construct.
    private MinecraftVersion(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private MinecraftVersion() {
      enum_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return lunarclient.apollo.common.v1.Version.internal_static_lunarclient_apollo_common_v1_MinecraftVersion_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return lunarclient.apollo.common.v1.Version.internal_static_lunarclient_apollo_common_v1_MinecraftVersion_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              lunarclient.apollo.common.v1.Version.MinecraftVersion.class, lunarclient.apollo.common.v1.Version.MinecraftVersion.Builder.class);
    }

    public static final int ENUM_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object enum_ = "";
    /**
     * <pre>
     * The enum encoding of this version. For example, "v1_8_9"
     * </pre>
     *
     * <code>string enum = 1 [json_name = "enum"];</code>
     * @return The enum.
     */
    @java.lang.Override
    public java.lang.String getEnum() {
      java.lang.Object ref = enum_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        enum_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * The enum encoding of this version. For example, "v1_8_9"
     * </pre>
     *
     * <code>string enum = 1 [json_name = "enum"];</code>
     * @return The bytes for enum.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEnumBytes() {
      java.lang.Object ref = enum_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        enum_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(enum_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, enum_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(enum_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, enum_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof lunarclient.apollo.common.v1.Version.MinecraftVersion)) {
        return super.equals(obj);
      }
      lunarclient.apollo.common.v1.Version.MinecraftVersion other = (lunarclient.apollo.common.v1.Version.MinecraftVersion) obj;

      if (!getEnum()
          .equals(other.getEnum())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ENUM_FIELD_NUMBER;
      hash = (53 * hash) + getEnum().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static lunarclient.apollo.common.v1.Version.MinecraftVersion parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lunarclient.apollo.common.v1.Version.MinecraftVersion parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lunarclient.apollo.common.v1.Version.MinecraftVersion parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lunarclient.apollo.common.v1.Version.MinecraftVersion parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lunarclient.apollo.common.v1.Version.MinecraftVersion parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lunarclient.apollo.common.v1.Version.MinecraftVersion parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lunarclient.apollo.common.v1.Version.MinecraftVersion parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static lunarclient.apollo.common.v1.Version.MinecraftVersion parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static lunarclient.apollo.common.v1.Version.MinecraftVersion parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static lunarclient.apollo.common.v1.Version.MinecraftVersion parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static lunarclient.apollo.common.v1.Version.MinecraftVersion parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static lunarclient.apollo.common.v1.Version.MinecraftVersion parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(lunarclient.apollo.common.v1.Version.MinecraftVersion prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * A reference to a specific version (released by Mojang) of Minecraft.
     * For example, Minecraft 1.8.9, or 1.19.4
     * </pre>
     *
     * Protobuf type {@code lunarclient.apollo.common.v1.MinecraftVersion}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:lunarclient.apollo.common.v1.MinecraftVersion)
        lunarclient.apollo.common.v1.Version.MinecraftVersionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return lunarclient.apollo.common.v1.Version.internal_static_lunarclient_apollo_common_v1_MinecraftVersion_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return lunarclient.apollo.common.v1.Version.internal_static_lunarclient_apollo_common_v1_MinecraftVersion_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                lunarclient.apollo.common.v1.Version.MinecraftVersion.class, lunarclient.apollo.common.v1.Version.MinecraftVersion.Builder.class);
      }

      // Construct using lunarclient.apollo.common.v1.Version.MinecraftVersion.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        enum_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return lunarclient.apollo.common.v1.Version.internal_static_lunarclient_apollo_common_v1_MinecraftVersion_descriptor;
      }

      @java.lang.Override
      public lunarclient.apollo.common.v1.Version.MinecraftVersion getDefaultInstanceForType() {
        return lunarclient.apollo.common.v1.Version.MinecraftVersion.getDefaultInstance();
      }

      @java.lang.Override
      public lunarclient.apollo.common.v1.Version.MinecraftVersion build() {
        lunarclient.apollo.common.v1.Version.MinecraftVersion result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public lunarclient.apollo.common.v1.Version.MinecraftVersion buildPartial() {
        lunarclient.apollo.common.v1.Version.MinecraftVersion result = new lunarclient.apollo.common.v1.Version.MinecraftVersion(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(lunarclient.apollo.common.v1.Version.MinecraftVersion result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.enum_ = enum_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof lunarclient.apollo.common.v1.Version.MinecraftVersion) {
          return mergeFrom((lunarclient.apollo.common.v1.Version.MinecraftVersion)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(lunarclient.apollo.common.v1.Version.MinecraftVersion other) {
        if (other == lunarclient.apollo.common.v1.Version.MinecraftVersion.getDefaultInstance()) return this;
        if (!other.getEnum().isEmpty()) {
          enum_ = other.enum_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                enum_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object enum_ = "";
      /**
       * <pre>
       * The enum encoding of this version. For example, "v1_8_9"
       * </pre>
       *
       * <code>string enum = 1 [json_name = "enum"];</code>
       * @return The enum.
       */
      public java.lang.String getEnum() {
        java.lang.Object ref = enum_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          enum_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * The enum encoding of this version. For example, "v1_8_9"
       * </pre>
       *
       * <code>string enum = 1 [json_name = "enum"];</code>
       * @return The bytes for enum.
       */
      public com.google.protobuf.ByteString
          getEnumBytes() {
        java.lang.Object ref = enum_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          enum_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * The enum encoding of this version. For example, "v1_8_9"
       * </pre>
       *
       * <code>string enum = 1 [json_name = "enum"];</code>
       * @param value The enum to set.
       * @return This builder for chaining.
       */
      public Builder setEnum(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        enum_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The enum encoding of this version. For example, "v1_8_9"
       * </pre>
       *
       * <code>string enum = 1 [json_name = "enum"];</code>
       * @return This builder for chaining.
       */
      public Builder clearEnum() {
        enum_ = getDefaultInstance().getEnum();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The enum encoding of this version. For example, "v1_8_9"
       * </pre>
       *
       * <code>string enum = 1 [json_name = "enum"];</code>
       * @param value The bytes for enum to set.
       * @return This builder for chaining.
       */
      public Builder setEnumBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        enum_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:lunarclient.apollo.common.v1.MinecraftVersion)
    }

    // @@protoc_insertion_point(class_scope:lunarclient.apollo.common.v1.MinecraftVersion)
    private static final lunarclient.apollo.common.v1.Version.MinecraftVersion DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new lunarclient.apollo.common.v1.Version.MinecraftVersion();
    }

    public static lunarclient.apollo.common.v1.Version.MinecraftVersion getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MinecraftVersion>
        PARSER = new com.google.protobuf.AbstractParser<MinecraftVersion>() {
      @java.lang.Override
      public MinecraftVersion parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<MinecraftVersion> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MinecraftVersion> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public lunarclient.apollo.common.v1.Version.MinecraftVersion getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface LunarClientVersionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:lunarclient.apollo.common.v1.LunarClientVersion)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * The Git branch this version was based on
     * </pre>
     *
     * <code>string git_branch = 1 [json_name = "gitBranch"];</code>
     * @return The gitBranch.
     */
    java.lang.String getGitBranch();
    /**
     * <pre>
     * The Git branch this version was based on
     * </pre>
     *
     * <code>string git_branch = 1 [json_name = "gitBranch"];</code>
     * @return The bytes for gitBranch.
     */
    com.google.protobuf.ByteString
        getGitBranchBytes();

    /**
     * <pre>
     * The Git commit this version was based on
     * </pre>
     *
     * <code>string git_commit = 2 [json_name = "gitCommit"];</code>
     * @return The gitCommit.
     */
    java.lang.String getGitCommit();
    /**
     * <pre>
     * The Git commit this version was based on
     * </pre>
     *
     * <code>string git_commit = 2 [json_name = "gitCommit"];</code>
     * @return The bytes for gitCommit.
     */
    com.google.protobuf.ByteString
        getGitCommitBytes();

    /**
     * <pre>
     * The semver encoding of this version. For example, "2.5.1"
     * </pre>
     *
     * <code>string semver = 3 [json_name = "semver"];</code>
     * @return The semver.
     */
    java.lang.String getSemver();
    /**
     * <pre>
     * The semver encoding of this version. For example, "2.5.1"
     * </pre>
     *
     * <code>string semver = 3 [json_name = "semver"];</code>
     * @return The bytes for semver.
     */
    com.google.protobuf.ByteString
        getSemverBytes();
  }
  /**
   * <pre>
   * A reference to a specific version (released by Moonsworth) of the
   * Lunar Client modpack.
   * </pre>
   *
   * Protobuf type {@code lunarclient.apollo.common.v1.LunarClientVersion}
   */
  public static final class LunarClientVersion extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:lunarclient.apollo.common.v1.LunarClientVersion)
      LunarClientVersionOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 1,
        /* suffix= */ "",
        LunarClientVersion.class.getName());
    }
    // Use LunarClientVersion.newBuilder() to construct.
    private LunarClientVersion(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private LunarClientVersion() {
      gitBranch_ = "";
      gitCommit_ = "";
      semver_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return lunarclient.apollo.common.v1.Version.internal_static_lunarclient_apollo_common_v1_LunarClientVersion_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return lunarclient.apollo.common.v1.Version.internal_static_lunarclient_apollo_common_v1_LunarClientVersion_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              lunarclient.apollo.common.v1.Version.LunarClientVersion.class, lunarclient.apollo.common.v1.Version.LunarClientVersion.Builder.class);
    }

    public static final int GIT_BRANCH_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object gitBranch_ = "";
    /**
     * <pre>
     * The Git branch this version was based on
     * </pre>
     *
     * <code>string git_branch = 1 [json_name = "gitBranch"];</code>
     * @return The gitBranch.
     */
    @java.lang.Override
    public java.lang.String getGitBranch() {
      java.lang.Object ref = gitBranch_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        gitBranch_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * The Git branch this version was based on
     * </pre>
     *
     * <code>string git_branch = 1 [json_name = "gitBranch"];</code>
     * @return The bytes for gitBranch.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getGitBranchBytes() {
      java.lang.Object ref = gitBranch_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gitBranch_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GIT_COMMIT_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object gitCommit_ = "";
    /**
     * <pre>
     * The Git commit this version was based on
     * </pre>
     *
     * <code>string git_commit = 2 [json_name = "gitCommit"];</code>
     * @return The gitCommit.
     */
    @java.lang.Override
    public java.lang.String getGitCommit() {
      java.lang.Object ref = gitCommit_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        gitCommit_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * The Git commit this version was based on
     * </pre>
     *
     * <code>string git_commit = 2 [json_name = "gitCommit"];</code>
     * @return The bytes for gitCommit.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getGitCommitBytes() {
      java.lang.Object ref = gitCommit_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gitCommit_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SEMVER_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object semver_ = "";
    /**
     * <pre>
     * The semver encoding of this version. For example, "2.5.1"
     * </pre>
     *
     * <code>string semver = 3 [json_name = "semver"];</code>
     * @return The semver.
     */
    @java.lang.Override
    public java.lang.String getSemver() {
      java.lang.Object ref = semver_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        semver_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * The semver encoding of this version. For example, "2.5.1"
     * </pre>
     *
     * <code>string semver = 3 [json_name = "semver"];</code>
     * @return The bytes for semver.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSemverBytes() {
      java.lang.Object ref = semver_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        semver_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(gitBranch_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, gitBranch_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(gitCommit_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, gitCommit_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(semver_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, semver_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(gitBranch_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, gitBranch_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(gitCommit_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, gitCommit_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(semver_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, semver_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof lunarclient.apollo.common.v1.Version.LunarClientVersion)) {
        return super.equals(obj);
      }
      lunarclient.apollo.common.v1.Version.LunarClientVersion other = (lunarclient.apollo.common.v1.Version.LunarClientVersion) obj;

      if (!getGitBranch()
          .equals(other.getGitBranch())) return false;
      if (!getGitCommit()
          .equals(other.getGitCommit())) return false;
      if (!getSemver()
          .equals(other.getSemver())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + GIT_BRANCH_FIELD_NUMBER;
      hash = (53 * hash) + getGitBranch().hashCode();
      hash = (37 * hash) + GIT_COMMIT_FIELD_NUMBER;
      hash = (53 * hash) + getGitCommit().hashCode();
      hash = (37 * hash) + SEMVER_FIELD_NUMBER;
      hash = (53 * hash) + getSemver().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static lunarclient.apollo.common.v1.Version.LunarClientVersion parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lunarclient.apollo.common.v1.Version.LunarClientVersion parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lunarclient.apollo.common.v1.Version.LunarClientVersion parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lunarclient.apollo.common.v1.Version.LunarClientVersion parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lunarclient.apollo.common.v1.Version.LunarClientVersion parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lunarclient.apollo.common.v1.Version.LunarClientVersion parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lunarclient.apollo.common.v1.Version.LunarClientVersion parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static lunarclient.apollo.common.v1.Version.LunarClientVersion parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static lunarclient.apollo.common.v1.Version.LunarClientVersion parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static lunarclient.apollo.common.v1.Version.LunarClientVersion parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static lunarclient.apollo.common.v1.Version.LunarClientVersion parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static lunarclient.apollo.common.v1.Version.LunarClientVersion parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(lunarclient.apollo.common.v1.Version.LunarClientVersion prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * A reference to a specific version (released by Moonsworth) of the
     * Lunar Client modpack.
     * </pre>
     *
     * Protobuf type {@code lunarclient.apollo.common.v1.LunarClientVersion}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:lunarclient.apollo.common.v1.LunarClientVersion)
        lunarclient.apollo.common.v1.Version.LunarClientVersionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return lunarclient.apollo.common.v1.Version.internal_static_lunarclient_apollo_common_v1_LunarClientVersion_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return lunarclient.apollo.common.v1.Version.internal_static_lunarclient_apollo_common_v1_LunarClientVersion_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                lunarclient.apollo.common.v1.Version.LunarClientVersion.class, lunarclient.apollo.common.v1.Version.LunarClientVersion.Builder.class);
      }

      // Construct using lunarclient.apollo.common.v1.Version.LunarClientVersion.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        gitBranch_ = "";
        gitCommit_ = "";
        semver_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return lunarclient.apollo.common.v1.Version.internal_static_lunarclient_apollo_common_v1_LunarClientVersion_descriptor;
      }

      @java.lang.Override
      public lunarclient.apollo.common.v1.Version.LunarClientVersion getDefaultInstanceForType() {
        return lunarclient.apollo.common.v1.Version.LunarClientVersion.getDefaultInstance();
      }

      @java.lang.Override
      public lunarclient.apollo.common.v1.Version.LunarClientVersion build() {
        lunarclient.apollo.common.v1.Version.LunarClientVersion result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public lunarclient.apollo.common.v1.Version.LunarClientVersion buildPartial() {
        lunarclient.apollo.common.v1.Version.LunarClientVersion result = new lunarclient.apollo.common.v1.Version.LunarClientVersion(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(lunarclient.apollo.common.v1.Version.LunarClientVersion result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.gitBranch_ = gitBranch_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.gitCommit_ = gitCommit_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.semver_ = semver_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof lunarclient.apollo.common.v1.Version.LunarClientVersion) {
          return mergeFrom((lunarclient.apollo.common.v1.Version.LunarClientVersion)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(lunarclient.apollo.common.v1.Version.LunarClientVersion other) {
        if (other == lunarclient.apollo.common.v1.Version.LunarClientVersion.getDefaultInstance()) return this;
        if (!other.getGitBranch().isEmpty()) {
          gitBranch_ = other.gitBranch_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getGitCommit().isEmpty()) {
          gitCommit_ = other.gitCommit_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getSemver().isEmpty()) {
          semver_ = other.semver_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                gitBranch_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                gitCommit_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                semver_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object gitBranch_ = "";
      /**
       * <pre>
       * The Git branch this version was based on
       * </pre>
       *
       * <code>string git_branch = 1 [json_name = "gitBranch"];</code>
       * @return The gitBranch.
       */
      public java.lang.String getGitBranch() {
        java.lang.Object ref = gitBranch_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          gitBranch_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * The Git branch this version was based on
       * </pre>
       *
       * <code>string git_branch = 1 [json_name = "gitBranch"];</code>
       * @return The bytes for gitBranch.
       */
      public com.google.protobuf.ByteString
          getGitBranchBytes() {
        java.lang.Object ref = gitBranch_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          gitBranch_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * The Git branch this version was based on
       * </pre>
       *
       * <code>string git_branch = 1 [json_name = "gitBranch"];</code>
       * @param value The gitBranch to set.
       * @return This builder for chaining.
       */
      public Builder setGitBranch(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        gitBranch_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The Git branch this version was based on
       * </pre>
       *
       * <code>string git_branch = 1 [json_name = "gitBranch"];</code>
       * @return This builder for chaining.
       */
      public Builder clearGitBranch() {
        gitBranch_ = getDefaultInstance().getGitBranch();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The Git branch this version was based on
       * </pre>
       *
       * <code>string git_branch = 1 [json_name = "gitBranch"];</code>
       * @param value The bytes for gitBranch to set.
       * @return This builder for chaining.
       */
      public Builder setGitBranchBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        gitBranch_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object gitCommit_ = "";
      /**
       * <pre>
       * The Git commit this version was based on
       * </pre>
       *
       * <code>string git_commit = 2 [json_name = "gitCommit"];</code>
       * @return The gitCommit.
       */
      public java.lang.String getGitCommit() {
        java.lang.Object ref = gitCommit_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          gitCommit_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * The Git commit this version was based on
       * </pre>
       *
       * <code>string git_commit = 2 [json_name = "gitCommit"];</code>
       * @return The bytes for gitCommit.
       */
      public com.google.protobuf.ByteString
          getGitCommitBytes() {
        java.lang.Object ref = gitCommit_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          gitCommit_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * The Git commit this version was based on
       * </pre>
       *
       * <code>string git_commit = 2 [json_name = "gitCommit"];</code>
       * @param value The gitCommit to set.
       * @return This builder for chaining.
       */
      public Builder setGitCommit(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        gitCommit_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The Git commit this version was based on
       * </pre>
       *
       * <code>string git_commit = 2 [json_name = "gitCommit"];</code>
       * @return This builder for chaining.
       */
      public Builder clearGitCommit() {
        gitCommit_ = getDefaultInstance().getGitCommit();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The Git commit this version was based on
       * </pre>
       *
       * <code>string git_commit = 2 [json_name = "gitCommit"];</code>
       * @param value The bytes for gitCommit to set.
       * @return This builder for chaining.
       */
      public Builder setGitCommitBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        gitCommit_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object semver_ = "";
      /**
       * <pre>
       * The semver encoding of this version. For example, "2.5.1"
       * </pre>
       *
       * <code>string semver = 3 [json_name = "semver"];</code>
       * @return The semver.
       */
      public java.lang.String getSemver() {
        java.lang.Object ref = semver_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          semver_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * The semver encoding of this version. For example, "2.5.1"
       * </pre>
       *
       * <code>string semver = 3 [json_name = "semver"];</code>
       * @return The bytes for semver.
       */
      public com.google.protobuf.ByteString
          getSemverBytes() {
        java.lang.Object ref = semver_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          semver_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * The semver encoding of this version. For example, "2.5.1"
       * </pre>
       *
       * <code>string semver = 3 [json_name = "semver"];</code>
       * @param value The semver to set.
       * @return This builder for chaining.
       */
      public Builder setSemver(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        semver_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The semver encoding of this version. For example, "2.5.1"
       * </pre>
       *
       * <code>string semver = 3 [json_name = "semver"];</code>
       * @return This builder for chaining.
       */
      public Builder clearSemver() {
        semver_ = getDefaultInstance().getSemver();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The semver encoding of this version. For example, "2.5.1"
       * </pre>
       *
       * <code>string semver = 3 [json_name = "semver"];</code>
       * @param value The bytes for semver to set.
       * @return This builder for chaining.
       */
      public Builder setSemverBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        semver_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:lunarclient.apollo.common.v1.LunarClientVersion)
    }

    // @@protoc_insertion_point(class_scope:lunarclient.apollo.common.v1.LunarClientVersion)
    private static final lunarclient.apollo.common.v1.Version.LunarClientVersion DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new lunarclient.apollo.common.v1.Version.LunarClientVersion();
    }

    public static lunarclient.apollo.common.v1.Version.LunarClientVersion getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LunarClientVersion>
        PARSER = new com.google.protobuf.AbstractParser<LunarClientVersion>() {
      @java.lang.Override
      public LunarClientVersion parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<LunarClientVersion> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LunarClientVersion> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public lunarclient.apollo.common.v1.Version.LunarClientVersion getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lunarclient_apollo_common_v1_MinecraftVersion_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lunarclient_apollo_common_v1_MinecraftVersion_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lunarclient_apollo_common_v1_LunarClientVersion_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lunarclient_apollo_common_v1_LunarClientVersion_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n*lunarclient/apollo/common/v1/version.p" +
      "roto\022\034lunarclient.apollo.common.v1\"&\n\020Mi" +
      "necraftVersion\022\022\n\004enum\030\001 \001(\tR\004enum\"j\n\022Lu" +
      "narClientVersion\022\035\n\ngit_branch\030\001 \001(\tR\tgi" +
      "tBranch\022\035\n\ngit_commit\030\002 \001(\tR\tgitCommit\022\026" +
      "\n\006semver\030\003 \001(\tR\006semverb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_lunarclient_apollo_common_v1_MinecraftVersion_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_lunarclient_apollo_common_v1_MinecraftVersion_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lunarclient_apollo_common_v1_MinecraftVersion_descriptor,
        new java.lang.String[] { "Enum", });
    internal_static_lunarclient_apollo_common_v1_LunarClientVersion_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_lunarclient_apollo_common_v1_LunarClientVersion_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lunarclient_apollo_common_v1_LunarClientVersion_descriptor,
        new java.lang.String[] { "GitBranch", "GitCommit", "Semver", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
